/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ADMISSION_ENCOUNTER extends TableImpl<Record> {

    private static final long serialVersionUID = -539303702;

    /**
     * The reference instance of <code>school.admission_encounter</code>
     */
    public static final ADMISSION_ENCOUNTER ADMISSION_ENCOUNTER = new ADMISSION_ENCOUNTER();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.admission_encounter.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.admission_encounter.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.admission_encounter.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.admission_encounter.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.admission_encounter.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.admission_encounter.admission_id</code>.
     */
    public final TableField<Record, Long> ADMISSION_ID = createField("admission_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.admission_encounter.encounter_id</code>.
     */
    public final TableField<Record, Long> ENCOUNTER_ID = createField("encounter_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.admission_encounter.ward_id</code>.
     */
    public final TableField<Record, Long> WARD_ID = createField("ward_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.admission_encounter</code> table reference
     */
    public ADMISSION_ENCOUNTER() {
        this("admission_encounter", null);
    }

    /**
     * Create an aliased <code>school.admission_encounter</code> table reference
     */
    public ADMISSION_ENCOUNTER(String alias) {
        this(alias, ADMISSION_ENCOUNTER);
    }

    private ADMISSION_ENCOUNTER(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ADMISSION_ENCOUNTER(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_ADMISSION_ENCOUNTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_ADMISSION_ENCOUNTER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_ADMISSION_ENCOUNTER_PRIMARY, Keys.KEY_ADMISSION_ENCOUNTER_UK_2CSQXEDJUCK9KDJ46ATGCKVKY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKEK0F2UFI2ISSYG5OA4V2ML6HU, Keys.FKT4RR16Q6WJ4AP97SOVG6NTYX0, Keys.FKG1E0H6E5ANR4000J8TPTPQLBY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ADMISSION_ENCOUNTER as(String alias) {
        return new ADMISSION_ENCOUNTER(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ADMISSION_ENCOUNTER rename(String name) {
        return new ADMISSION_ENCOUNTER(name, null);
    }
}
