/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class APPOINTMENT_RESCHEDULLING_REASON extends TableImpl<Record> {

    private static final long serialVersionUID = -675313151;

    /**
     * The reference instance of <code>school.appointment_reschedulling_reason</code>
     */
    public static final APPOINTMENT_RESCHEDULLING_REASON APPOINTMENT_RESCHEDULLING_REASON = new APPOINTMENT_RESCHEDULLING_REASON();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.appointment_reschedulling_reason.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.appointment_reschedulling_reason.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.appointment_reschedulling_reason.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.appointment_reschedulling_reason.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.appointment_reschedulling_reason.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.appointment_reschedulling_reason.name</code>.
     */
    public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>school.appointment_reschedulling_reason</code> table reference
     */
    public APPOINTMENT_RESCHEDULLING_REASON() {
        this("appointment_reschedulling_reason", null);
    }

    /**
     * Create an aliased <code>school.appointment_reschedulling_reason</code> table reference
     */
    public APPOINTMENT_RESCHEDULLING_REASON(String alias) {
        this(alias, APPOINTMENT_RESCHEDULLING_REASON);
    }

    private APPOINTMENT_RESCHEDULLING_REASON(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private APPOINTMENT_RESCHEDULLING_REASON(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_APPOINTMENT_RESCHEDULLING_REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_APPOINTMENT_RESCHEDULLING_REASON_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_APPOINTMENT_RESCHEDULLING_REASON_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public APPOINTMENT_RESCHEDULLING_REASON as(String alias) {
        return new APPOINTMENT_RESCHEDULLING_REASON(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public APPOINTMENT_RESCHEDULLING_REASON rename(String name) {
        return new APPOINTMENT_RESCHEDULLING_REASON(name, null);
    }
}
