/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ART_VISIT extends TableImpl<Record> {

    private static final long serialVersionUID = -1918429464;

    /**
     * The reference instance of <code>school.art_visit</code>
     */
    public static final ART_VISIT ART_VISIT = new ART_VISIT();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.art_visit.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.art_visit.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.art_visit.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.art_visit.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.art_visit.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.art_visit.date</code>.
     */
    public final TableField<Record, Date> DATE = createField("date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>school.art_visit.art_id</code>.
     */
    public final TableField<Record, Long> ART_ID = createField("art_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.art_visit.art_visit_status_id</code>.
     */
    public final TableField<Record, Long> ART_VISIT_STATUS_ID = createField("art_visit_status_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.art_visit.art_visit_type_id</code>.
     */
    public final TableField<Record, Long> ART_VISIT_TYPE_ID = createField("art_visit_type_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.art_visit.encounter_id</code>.
     */
    public final TableField<Record, Long> ENCOUNTER_ID = createField("encounter_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>school.art_visit</code> table reference
     */
    public ART_VISIT() {
        this("art_visit", null);
    }

    /**
     * Create an aliased <code>school.art_visit</code> table reference
     */
    public ART_VISIT(String alias) {
        this(alias, ART_VISIT);
    }

    private ART_VISIT(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ART_VISIT(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_ART_VISIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_ART_VISIT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_ART_VISIT_PRIMARY, Keys.KEY_ART_VISIT_UK_9HOYGVC7QJ4168JL08NHXEJL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKBWCN4EA4I35RI8A2PBYAC8YN4, Keys.FKQ8LF9RRFLRMT72OX3IBRME04A, Keys.FK7Q0XVRB68YQ5PEWXC119M04WW, Keys.FK1C78FEYOXM2VQ2A22FJK2AK86);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ART_VISIT as(String alias) {
        return new ART_VISIT(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ART_VISIT rename(String name) {
        return new ART_VISIT(name, null);
    }
}
