/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ART_INVESTIGATION_HISTORY extends TableImpl<Record> {

    private static final long serialVersionUID = 1198173082;

    /**
     * The reference instance of <code>school.art_investigation_history</code>
     */
    public static final ART_INVESTIGATION_HISTORY ART_INVESTIGATION_HISTORY = new ART_INVESTIGATION_HISTORY();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.art_investigation_history.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.art_investigation_history.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.art_investigation_history.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.art_investigation_history.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.art_investigation_history.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.art_investigation_history.art_id</code>.
     */
    public final TableField<Record, Long> ART_ID = createField("art_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.art_investigation_history.person_investigation_id</code>.
     */
    public final TableField<Record, Long> PERSON_INVESTIGATION_ID = createField("person_investigation_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.art_investigation_history</code> table reference
     */
    public ART_INVESTIGATION_HISTORY() {
        this("art_investigation_history", null);
    }

    /**
     * Create an aliased <code>school.art_investigation_history</code> table reference
     */
    public ART_INVESTIGATION_HISTORY(String alias) {
        this(alias, ART_INVESTIGATION_HISTORY);
    }

    private ART_INVESTIGATION_HISTORY(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ART_INVESTIGATION_HISTORY(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_ART_INVESTIGATION_HISTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_ART_INVESTIGATION_HISTORY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_ART_INVESTIGATION_HISTORY_PRIMARY, Keys.KEY_ART_INVESTIGATION_HISTORY_UK_JNYHYYUU5EHSCKRQE09B01N84);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKOCW16Q2XSAAA4C2887OXYLT69, Keys.FK7N48L16S2A0M3N5NC99OE6UHC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ART_INVESTIGATION_HISTORY as(String alias) {
        return new ART_INVESTIGATION_HISTORY(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ART_INVESTIGATION_HISTORY rename(String name) {
        return new ART_INVESTIGATION_HISTORY(name, null);
    }
}
