/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ARV_COMBINATION_REGIMEN extends TableImpl<Record> {

    private static final long serialVersionUID = -2020487749;

    /**
     * The reference instance of <code>school.arv_combination_regimen</code>
     */
    public static final ARV_COMBINATION_REGIMEN ARV_COMBINATION_REGIMEN = new ARV_COMBINATION_REGIMEN();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.arv_combination_regimen.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.arv_combination_regimen.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.arv_combination_regimen.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.arv_combination_regimen.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.arv_combination_regimen.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.arv_combination_regimen.code</code>.
     */
    public final TableField<Record, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>school.arv_combination_regimen.name</code>.
     */
    public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>school.arv_combination_regimen.drug_id</code>.
     */
    public final TableField<Record, Long> DRUG_ID = createField("drug_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.arv_combination_regimen</code> table reference
     */
    public ARV_COMBINATION_REGIMEN() {
        this("arv_combination_regimen", null);
    }

    /**
     * Create an aliased <code>school.arv_combination_regimen</code> table reference
     */
    public ARV_COMBINATION_REGIMEN(String alias) {
        this(alias, ARV_COMBINATION_REGIMEN);
    }

    private ARV_COMBINATION_REGIMEN(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ARV_COMBINATION_REGIMEN(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_ARV_COMBINATION_REGIMEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_ARV_COMBINATION_REGIMEN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_ARV_COMBINATION_REGIMEN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKR4TTASBTXEF9725YM8P808WYK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ARV_COMBINATION_REGIMEN as(String alias) {
        return new ARV_COMBINATION_REGIMEN(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ARV_COMBINATION_REGIMEN rename(String name) {
        return new ARV_COMBINATION_REGIMEN(name, null);
    }
}
