/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CONTRACTION extends TableImpl<Record> {

    private static final long serialVersionUID = -749885447;

    /**
     * The reference instance of <code>school.contraction</code>
     */
    public static final CONTRACTION CONTRACTION = new CONTRACTION();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.contraction.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.contraction.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.contraction.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.contraction.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.contraction.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.contraction.date</code>.
     */
    public final TableField<Record, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.contraction.dilation</code>.
     */
    public final TableField<Record, Double> DILATION = createField("dilation", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>school.contraction.frequency</code>.
     */
    public final TableField<Record, Double> FREQUENCY = createField("frequency", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>school.contraction.strength</code>.
     */
    public final TableField<Record, String> STRENGTH = createField("strength", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.contraction.delivery_id</code>.
     */
    public final TableField<Record, Long> DELIVERY_ID = createField("delivery_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.contraction</code> table reference
     */
    public CONTRACTION() {
        this("contraction", null);
    }

    /**
     * Create an aliased <code>school.contraction</code> table reference
     */
    public CONTRACTION(String alias) {
        this(alias, CONTRACTION);
    }

    private CONTRACTION(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private CONTRACTION(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_CONTRACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_CONTRACTION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_CONTRACTION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK7RHQKP2BJWMI41XOVNMHOJT0F);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CONTRACTION as(String alias) {
        return new CONTRACTION(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CONTRACTION rename(String name) {
        return new CONTRACTION(name, null);
    }
}
