/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DELIVERY_MATERNAL_DEATH_FACTOR extends TableImpl<Record> {

    private static final long serialVersionUID = 71009228;

    /**
     * The reference instance of <code>school.delivery_maternal_death_factor</code>
     */
    public static final DELIVERY_MATERNAL_DEATH_FACTOR DELIVERY_MATERNAL_DEATH_FACTOR = new DELIVERY_MATERNAL_DEATH_FACTOR();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.delivery_maternal_death_factor.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery_maternal_death_factor.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.delivery_maternal_death_factor.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.delivery_maternal_death_factor.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.delivery_maternal_death_factor.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.delivery_maternal_death_factor.state</code>.
     */
    public final TableField<Record, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>school.delivery_maternal_death_factor.maternal_death_id</code>.
     */
    public final TableField<Record, Long> MATERNAL_DEATH_ID = createField("maternal_death_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery_maternal_death_factor.maternal_death_factor_id</code>.
     */
    public final TableField<Record, Long> MATERNAL_DEATH_FACTOR_ID = createField("maternal_death_factor_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.delivery_maternal_death_factor</code> table reference
     */
    public DELIVERY_MATERNAL_DEATH_FACTOR() {
        this("delivery_maternal_death_factor", null);
    }

    /**
     * Create an aliased <code>school.delivery_maternal_death_factor</code> table reference
     */
    public DELIVERY_MATERNAL_DEATH_FACTOR(String alias) {
        this(alias, DELIVERY_MATERNAL_DEATH_FACTOR);
    }

    private DELIVERY_MATERNAL_DEATH_FACTOR(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private DELIVERY_MATERNAL_DEATH_FACTOR(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_DELIVERY_MATERNAL_DEATH_FACTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_DELIVERY_MATERNAL_DEATH_FACTOR_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_DELIVERY_MATERNAL_DEATH_FACTOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKSWE6NN2RP27PYGG2ACTBAOL95, Keys.FKGX92S8GOQHO1BQ2VQGHP2EU9A);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DELIVERY_MATERNAL_DEATH_FACTOR as(String alias) {
        return new DELIVERY_MATERNAL_DEATH_FACTOR(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DELIVERY_MATERNAL_DEATH_FACTOR rename(String name) {
        return new DELIVERY_MATERNAL_DEATH_FACTOR(name, null);
    }
}
