/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DELIVERY_SUMMARY extends TableImpl<Record> {

    private static final long serialVersionUID = -2040416789;

    /**
     * The reference instance of <code>school.delivery_summary</code>
     */
    public static final DELIVERY_SUMMARY DELIVERY_SUMMARY = new DELIVERY_SUMMARY();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.delivery_summary.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery_summary.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.delivery_summary.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.delivery_summary.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.delivery_summary.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.delivery_summary.assisted_by</code>.
     */
    public final TableField<Record, String> ASSISTED_BY = createField("assisted_by", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.delivery_summary.blood_loss</code>.
     */
    public final TableField<Record, Long> BLOOD_LOSS = createField("blood_loss", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.delivery_summary.delivered_by</code>.
     */
    public final TableField<Record, String> DELIVERED_BY = createField("delivered_by", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.delivery_summary.estimated_blood_loss</code>.
     */
    public final TableField<Record, Long> ESTIMATED_BLOOD_LOSS = createField("estimated_blood_loss", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.delivery_summary.measured_blood_loss</code>.
     */
    public final TableField<Record, Long> MEASURED_BLOOD_LOSS = createField("measured_blood_loss", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.delivery_summary.method_of_repair</code>.
     */
    public final TableField<Record, String> METHOD_OF_REPAIR = createField("method_of_repair", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.delivery_summary.perineum</code>.
     */
    public final TableField<Record, String> PERINEUM = createField("perineum", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.delivery_summary.pph</code>.
     */
    public final TableField<Record, String> PPH = createField("pph", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.delivery_summary.repaired_by</code>.
     */
    public final TableField<Record, String> REPAIRED_BY = createField("repaired_by", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.delivery_summary.suture_type</code>.
     */
    public final TableField<Record, String> SUTURE_TYPE = createField("suture_type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.delivery_summary.total_blood_loss</code>.
     */
    public final TableField<Record, Long> TOTAL_BLOOD_LOSS = createField("total_blood_loss", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.delivery_summary.uterus_contracted</code>.
     */
    public final TableField<Record, String> UTERUS_CONTRACTED = createField("uterus_contracted", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.delivery_summary.bp_after_delivery_id</code>.
     */
    public final TableField<Record, Long> BP_AFTER_DELIVERY_ID = createField("bp_after_delivery_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.delivery_summary.bp_after_hr_delivery_id</code>.
     */
    public final TableField<Record, Long> BP_AFTER_HR_DELIVERY_ID = createField("bp_after_hr_delivery_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.delivery_summary.degree_id</code>.
     */
    public final TableField<Record, Long> DEGREE_ID = createField("degree_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.delivery_summary.pulse_after_delivery_id</code>.
     */
    public final TableField<Record, Long> PULSE_AFTER_DELIVERY_ID = createField("pulse_after_delivery_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.delivery_summary.pulse_after_hr_delivery_id</code>.
     */
    public final TableField<Record, Long> PULSE_AFTER_HR_DELIVERY_ID = createField("pulse_after_hr_delivery_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.delivery_summary.temp_after_delivery_id</code>.
     */
    public final TableField<Record, Long> TEMP_AFTER_DELIVERY_ID = createField("temp_after_delivery_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>school.delivery_summary</code> table reference
     */
    public DELIVERY_SUMMARY() {
        this("delivery_summary", null);
    }

    /**
     * Create an aliased <code>school.delivery_summary</code> table reference
     */
    public DELIVERY_SUMMARY(String alias) {
        this(alias, DELIVERY_SUMMARY);
    }

    private DELIVERY_SUMMARY(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private DELIVERY_SUMMARY(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_DELIVERY_SUMMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_DELIVERY_SUMMARY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_DELIVERY_SUMMARY_PRIMARY, Keys.KEY_DELIVERY_SUMMARY_UK_4JIESA1XUPG4LHFD16HTMTHTJ, Keys.KEY_DELIVERY_SUMMARY_UK_5XFEGJKPS2V69S6IPOKN6NHLO, Keys.KEY_DELIVERY_SUMMARY_UK_5XG9X8J310YGIUMF0N7F7NCX5, Keys.KEY_DELIVERY_SUMMARY_UK_LKG7SI0A8R4NIENLOYSBCBP0R, Keys.KEY_DELIVERY_SUMMARY_UK_R0OTBRJ9NI3MCK9N8S1BSNO5U);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK9Y4K19HW0CQ31NS6TL8TM5HPM, Keys.FK9B2030R7KGLO7LVSPO4SNA7VW, Keys.FKGF2IKKORJE9UF9B9QQVNY4NCU, Keys.FKKXLM0D18OAN7YAOGL0MJ9ANJV, Keys.FK3XWT0SSHP787416G7XU8B01H7, Keys.FK57PL0YCH0Q5O1AC6MHE94O0XY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DELIVERY_SUMMARY as(String alias) {
        return new DELIVERY_SUMMARY(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DELIVERY_SUMMARY rename(String name) {
        return new DELIVERY_SUMMARY(name, null);
    }
}
