/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DELIVERY_HISTORY extends TableImpl<Record> {

    private static final long serialVersionUID = -688717409;

    /**
     * The reference instance of <code>school.delivery_history</code>
     */
    public static final DELIVERY_HISTORY DELIVERY_HISTORY = new DELIVERY_HISTORY();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.delivery_history.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery_history.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.delivery_history.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.delivery_history.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.delivery_history.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.delivery_history.contraction</code>.
     */
    public final TableField<Record, Boolean> CONTRACTION = createField("contraction", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>school.delivery_history.duration</code>.
     */
    public final TableField<Record, String> DURATION = createField("duration", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.delivery_history.membranes_ruptured</code>.
     */
    public final TableField<Record, Boolean> MEMBRANES_RUPTURED = createField("membranes_ruptured", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>school.delivery_history.show_present</code>.
     */
    public final TableField<Record, Boolean> SHOW_PRESENT = createField("show_present", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>school.delivery_history.time_of_on_set</code>.
     */
    public final TableField<Record, Timestamp> TIME_OF_ON_SET = createField("time_of_on_set", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.delivery_history.time_of_rupture</code>.
     */
    public final TableField<Record, Timestamp> TIME_OF_RUPTURE = createField("time_of_rupture", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>school.delivery_history</code> table reference
     */
    public DELIVERY_HISTORY() {
        this("delivery_history", null);
    }

    /**
     * Create an aliased <code>school.delivery_history</code> table reference
     */
    public DELIVERY_HISTORY(String alias) {
        this(alias, DELIVERY_HISTORY);
    }

    private DELIVERY_HISTORY(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private DELIVERY_HISTORY(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_DELIVERY_HISTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_DELIVERY_HISTORY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_DELIVERY_HISTORY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DELIVERY_HISTORY as(String alias) {
        return new DELIVERY_HISTORY(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DELIVERY_HISTORY rename(String name) {
        return new DELIVERY_HISTORY(name, null);
    }
}
