/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DELIVERY extends TableImpl<Record> {

    private static final long serialVersionUID = 1112447888;

    /**
     * The reference instance of <code>school.delivery</code>
     */
    public static final DELIVERY DELIVERY = new DELIVERY();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.delivery.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.delivery.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.delivery.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.delivery.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.delivery.date</code>.
     */
    public final TableField<Record, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.delivery.partogram_note</code>.
     */
    public final TableField<Record, String> PARTOGRAM_NOTE = createField("partogram_note", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.delivery.state</code>.
     */
    public final TableField<Record, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>school.delivery.admission_id</code>.
     */
    public final TableField<Record, Long> ADMISSION_ID = createField("admission_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.delivery.delivery_summary_id</code>.
     */
    public final TableField<Record, Long> DELIVERY_SUMMARY_ID = createField("delivery_summary_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery.doctor_examination_id</code>.
     */
    public final TableField<Record, Long> DOCTOR_EXAMINATION_ID = createField("doctor_examination_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery.doctor_general_examination_id</code>.
     */
    public final TableField<Record, Long> DOCTOR_GENERAL_EXAMINATION_ID = createField("doctor_general_examination_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery.history_id</code>.
     */
    public final TableField<Record, Long> HISTORY_ID = createField("history_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery.labour_summary_id</code>.
     */
    public final TableField<Record, Long> LABOUR_SUMMARY_ID = createField("labour_summary_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery.nurse_examination_id</code>.
     */
    public final TableField<Record, Long> NURSE_EXAMINATION_ID = createField("nurse_examination_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery.nurse_general_examination_id</code>.
     */
    public final TableField<Record, Long> NURSE_GENERAL_EXAMINATION_ID = createField("nurse_general_examination_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery.person_id</code>.
     */
    public final TableField<Record, Long> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery.placenta_and_membrane_id</code>.
     */
    public final TableField<Record, Long> PLACENTA_AND_MEMBRANE_ID = createField("placenta_and_membrane_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.delivery.pnc_id</code>.
     */
    public final TableField<Record, Long> PNC_ID = createField("pnc_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>school.delivery</code> table reference
     */
    public DELIVERY() {
        this("delivery", null);
    }

    /**
     * Create an aliased <code>school.delivery</code> table reference
     */
    public DELIVERY(String alias) {
        this(alias, DELIVERY);
    }

    private DELIVERY(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private DELIVERY(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_DELIVERY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_DELIVERY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_DELIVERY_PRIMARY, Keys.KEY_DELIVERY_UK_OMI63D9F2I0UDC5FTY5FF8LHF, Keys.KEY_DELIVERY_UK_55RL1PAJ24P6MH9EVUFKIKSH3, Keys.KEY_DELIVERY_UK_EIOK1O2M8TSDX82MA8UNCL8UQ, Keys.KEY_DELIVERY_UK_JFJW1B79QWN2LKXW4Y7U5HVKX, Keys.KEY_DELIVERY_UK_RR061FOISVYDACGRAC7DX8C7Q, Keys.KEY_DELIVERY_UK_M9O6TH8DGR3TRM8BQ221QAKAC, Keys.KEY_DELIVERY_UK_2RXOUQRGGOAI9Y3WX962RXFV, Keys.KEY_DELIVERY_UK_87N097IIC47YNRY3FLHEKV322, Keys.KEY_DELIVERY_UK_MPQU9TYU28A3PL9BKI9U6SSKW, Keys.KEY_DELIVERY_UK_IMRWMIPTFRC0HPWSYJ3G29KSU);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKLXD63C7O9A0IAJTL2JUT263V4, Keys.FKLXM4Y1O9A4W1A22L0BHJUIMG6, Keys.FK69K6M1346WO1PFF72AKQMH42K, Keys.FKQ78NY4UJGPUX4A5GQAKR12CS9, Keys.FKDL6891XKC2E6FPG93POUNKL2A, Keys.FK2O5OIVUPXYQJK3TA8F29EGCAP, Keys.FKI8SUUAWMVMO40ABO1KMVDQ6PI, Keys.FKRQQTCE6I3KQKSRO1NW3LXKHYX, Keys.FKTDX2SOUOGJ7IJJI3RKKGTJ50R, Keys.FKHLRKWDB09CNKXIFPYWD99RYP3, Keys.FK7C56WHIAM8X99LBWLJJ3K4CXW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DELIVERY as(String alias) {
        return new DELIVERY(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DELIVERY rename(String name) {
        return new DELIVERY(name, null);
    }
}
