/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DRUG_NAME extends TableImpl<Record> {

    private static final long serialVersionUID = -332000019;

    /**
     * The reference instance of <code>school.drug_name</code>
     */
    public static final DRUG_NAME DRUG_NAME = new DRUG_NAME();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.drug_name.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.drug_name.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.drug_name.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.drug_name.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.drug_name.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.drug_name.alias</code>.
     */
    public final TableField<Record, String> ALIAS = createField("alias", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.drug_name.categry</code>.
     */
    public final TableField<Record, String> CATEGRY = createField("categry", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.drug_name.code</code>.
     */
    public final TableField<Record, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>school.drug_name.is_otc</code>.
     */
    public final TableField<Record, Boolean> IS_OTC = createField("is_otc", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

    /**
     * The column <code>school.drug_name.level</code>.
     */
    public final TableField<Record, String> LEVEL = createField("level", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.drug_name.name</code>.
     */
    public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>school.drug_name.standard_id</code>.
     */
    public final TableField<Record, Long> STANDARD_ID = createField("standard_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.drug_name</code> table reference
     */
    public DRUG_NAME() {
        this("drug_name", null);
    }

    /**
     * Create an aliased <code>school.drug_name</code> table reference
     */
    public DRUG_NAME(String alias) {
        this(alias, DRUG_NAME);
    }

    private DRUG_NAME(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private DRUG_NAME(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_DRUG_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_DRUG_NAME_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_DRUG_NAME_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK6SR4WD4Y7Y8KKT1XQGOFWX5KI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DRUG_NAME as(String alias) {
        return new DRUG_NAME(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DRUG_NAME rename(String name) {
        return new DRUG_NAME(name, null);
    }
}
