/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ENCOUNTER_HEALTH_EDUCATION extends TableImpl<Record> {

    private static final long serialVersionUID = -5068062;

    /**
     * The reference instance of <code>school.encounter_health_education</code>
     */
    public static final ENCOUNTER_HEALTH_EDUCATION ENCOUNTER_HEALTH_EDUCATION = new ENCOUNTER_HEALTH_EDUCATION();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.encounter_health_education.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.encounter_health_education.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.encounter_health_education.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.encounter_health_education.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.encounter_health_education.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.encounter_health_education.encounter_id</code>.
     */
    public final TableField<Record, Long> ENCOUNTER_ID = createField("encounter_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.encounter_health_education.person_health_education_id</code>.
     */
    public final TableField<Record, Long> PERSON_HEALTH_EDUCATION_ID = createField("person_health_education_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.encounter_health_education</code> table reference
     */
    public ENCOUNTER_HEALTH_EDUCATION() {
        this("encounter_health_education", null);
    }

    /**
     * Create an aliased <code>school.encounter_health_education</code> table reference
     */
    public ENCOUNTER_HEALTH_EDUCATION(String alias) {
        this(alias, ENCOUNTER_HEALTH_EDUCATION);
    }

    private ENCOUNTER_HEALTH_EDUCATION(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ENCOUNTER_HEALTH_EDUCATION(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_ENCOUNTER_HEALTH_EDUCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_ENCOUNTER_HEALTH_EDUCATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_ENCOUNTER_HEALTH_EDUCATION_PRIMARY, Keys.KEY_ENCOUNTER_HEALTH_EDUCATION_UK_J8WMCCYR59CKAQX9KHDY2L317);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKR27S653TVSPMJ8Q0HLTNQJFFP, Keys.FKPK7JDQQQUJ0BIE2FV06LR3MKM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ENCOUNTER_HEALTH_EDUCATION as(String alias) {
        return new ENCOUNTER_HEALTH_EDUCATION(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ENCOUNTER_HEALTH_EDUCATION rename(String name) {
        return new ENCOUNTER_HEALTH_EDUCATION(name, null);
    }
}
