/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ENCOUNTER_COMPLAINT extends TableImpl<Record> {

    private static final long serialVersionUID = 1628071283;

    /**
     * The reference instance of <code>school.encounter_complaint</code>
     */
    public static final ENCOUNTER_COMPLAINT ENCOUNTER_COMPLAINT = new ENCOUNTER_COMPLAINT();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.encounter_complaint.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.encounter_complaint.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.encounter_complaint.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.encounter_complaint.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.encounter_complaint.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.encounter_complaint.encounter_id</code>.
     */
    public final TableField<Record, Long> ENCOUNTER_ID = createField("encounter_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.encounter_complaint.person_complaint_id</code>.
     */
    public final TableField<Record, Long> PERSON_COMPLAINT_ID = createField("person_complaint_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.encounter_complaint</code> table reference
     */
    public ENCOUNTER_COMPLAINT() {
        this("encounter_complaint", null);
    }

    /**
     * Create an aliased <code>school.encounter_complaint</code> table reference
     */
    public ENCOUNTER_COMPLAINT(String alias) {
        this(alias, ENCOUNTER_COMPLAINT);
    }

    private ENCOUNTER_COMPLAINT(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ENCOUNTER_COMPLAINT(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_ENCOUNTER_COMPLAINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_ENCOUNTER_COMPLAINT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_ENCOUNTER_COMPLAINT_PRIMARY, Keys.KEY_ENCOUNTER_COMPLAINT_UK_T3300WYELVAWAVYC4J4X6BE2A);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKB0DUDINV3GM3PHHP8OW7MYHTQ, Keys.FK96BOP7TP5JQE2MEYQ6JWJ5HY5);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ENCOUNTER_COMPLAINT as(String alias) {
        return new ENCOUNTER_COMPLAINT(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ENCOUNTER_COMPLAINT rename(String name) {
        return new ENCOUNTER_COMPLAINT(name, null);
    }
}
