/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ENCOUNTER_DIAGNOSIS extends TableImpl<Record> {

    private static final long serialVersionUID = -1425826511;

    /**
     * The reference instance of <code>school.encounter_diagnosis</code>
     */
    public static final ENCOUNTER_DIAGNOSIS ENCOUNTER_DIAGNOSIS = new ENCOUNTER_DIAGNOSIS();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.encounter_diagnosis.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.encounter_diagnosis.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.encounter_diagnosis.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.encounter_diagnosis.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.encounter_diagnosis.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.encounter_diagnosis.encounter_id</code>.
     */
    public final TableField<Record, Long> ENCOUNTER_ID = createField("encounter_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.encounter_diagnosis.person_diagnosis_id</code>.
     */
    public final TableField<Record, Long> PERSON_DIAGNOSIS_ID = createField("person_diagnosis_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.encounter_diagnosis</code> table reference
     */
    public ENCOUNTER_DIAGNOSIS() {
        this("encounter_diagnosis", null);
    }

    /**
     * Create an aliased <code>school.encounter_diagnosis</code> table reference
     */
    public ENCOUNTER_DIAGNOSIS(String alias) {
        this(alias, ENCOUNTER_DIAGNOSIS);
    }

    private ENCOUNTER_DIAGNOSIS(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ENCOUNTER_DIAGNOSIS(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_ENCOUNTER_DIAGNOSIS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_ENCOUNTER_DIAGNOSIS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_ENCOUNTER_DIAGNOSIS_PRIMARY, Keys.KEY_ENCOUNTER_DIAGNOSIS_UK_6DNDWY913PWU9PT7OUIYYCUPJ);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKRF8NECVWJU6XCY847BK9G5OPP, Keys.FK4GWJKQCQ77FIBAE98HQYTV3VC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ENCOUNTER_DIAGNOSIS as(String alias) {
        return new ENCOUNTER_DIAGNOSIS(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ENCOUNTER_DIAGNOSIS rename(String name) {
        return new ENCOUNTER_DIAGNOSIS(name, null);
    }
}
