/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IMMUNIZATION_SCHEDULE extends TableImpl<Record> {

    private static final long serialVersionUID = -649918195;

    /**
     * The reference instance of <code>school.immunization_schedule</code>
     */
    public static final IMMUNIZATION_SCHEDULE IMMUNIZATION_SCHEDULE = new IMMUNIZATION_SCHEDULE();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.immunization_schedule.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.immunization_schedule.primary_drug</code>.
     */
    public final TableField<Record, Boolean> PRIMARY_DRUG = createField("primary_drug", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

    /**
     * The column <code>school.immunization_schedule.timeline</code>.
     */
    public final TableField<Record, Integer> TIMELINE = createField("timeline", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>school.immunization_schedule.drug_name_id</code>.
     */
    public final TableField<Record, Long> DRUG_NAME_ID = createField("drug_name_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.immunization_schedule.drug_option_id</code>.
     */
    public final TableField<Record, Long> DRUG_OPTION_ID = createField("drug_option_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>school.immunization_schedule</code> table reference
     */
    public IMMUNIZATION_SCHEDULE() {
        this("immunization_schedule", null);
    }

    /**
     * Create an aliased <code>school.immunization_schedule</code> table reference
     */
    public IMMUNIZATION_SCHEDULE(String alias) {
        this(alias, IMMUNIZATION_SCHEDULE);
    }

    private IMMUNIZATION_SCHEDULE(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private IMMUNIZATION_SCHEDULE(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_IMMUNIZATION_SCHEDULE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_IMMUNIZATION_SCHEDULE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKXBUK11N396RXMQK49JK76WUX, Keys.FKPDPG4H6T6CY5MLAENH8F6FCDM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IMMUNIZATION_SCHEDULE as(String alias) {
        return new IMMUNIZATION_SCHEDULE(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IMMUNIZATION_SCHEDULE rename(String name) {
        return new IMMUNIZATION_SCHEDULE(name, null);
    }
}
