/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IMNCI_CLASSIFICATION extends TableImpl<Record> {

    private static final long serialVersionUID = -432352999;

    /**
     * The reference instance of <code>school.imnci_classification</code>
     */
    public static final IMNCI_CLASSIFICATION IMNCI_CLASSIFICATION = new IMNCI_CLASSIFICATION();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.imnci_classification.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.imnci_classification.category_id</code>.
     */
    public final TableField<Record, Long> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.imnci_classification.encounter_diagnosis_id</code>.
     */
    public final TableField<Record, Long> ENCOUNTER_DIAGNOSIS_ID = createField("encounter_diagnosis_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.imnci_classification.imnci_visit_id</code>.
     */
    public final TableField<Record, Long> IMNCI_VISIT_ID = createField("imnci_visit_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.imnci_classification</code> table reference
     */
    public IMNCI_CLASSIFICATION() {
        this("imnci_classification", null);
    }

    /**
     * Create an aliased <code>school.imnci_classification</code> table reference
     */
    public IMNCI_CLASSIFICATION(String alias) {
        this(alias, IMNCI_CLASSIFICATION);
    }

    private IMNCI_CLASSIFICATION(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private IMNCI_CLASSIFICATION(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_IMNCI_CLASSIFICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_IMNCI_CLASSIFICATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_IMNCI_CLASSIFICATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKC9TIM7KL6DYY39X03HT0B6LPU, Keys.FKPTQ0JM170PYVBDV9P5VSUODHV, Keys.FKI7TOSJX3WK5PACON3UINBU700);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IMNCI_CLASSIFICATION as(String alias) {
        return new IMNCI_CLASSIFICATION(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IMNCI_CLASSIFICATION rename(String name) {
        return new IMNCI_CLASSIFICATION(name, null);
    }
}
