/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JHI_AUTHORITY extends TableImpl<Record> {

    private static final long serialVersionUID = 1368237618;

    /**
     * The reference instance of <code>school.jhi_authority</code>
     */
    public static final JHI_AUTHORITY JHI_AUTHORITY = new JHI_AUTHORITY();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.jhi_authority.name</code>.
     */
    public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * Create a <code>school.jhi_authority</code> table reference
     */
    public JHI_AUTHORITY() {
        this("jhi_authority", null);
    }

    /**
     * Create an aliased <code>school.jhi_authority</code> table reference
     */
    public JHI_AUTHORITY(String alias) {
        this(alias, JHI_AUTHORITY);
    }

    private JHI_AUTHORITY(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private JHI_AUTHORITY(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_JHI_AUTHORITY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_JHI_AUTHORITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JHI_AUTHORITY as(String alias) {
        return new JHI_AUTHORITY(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JHI_AUTHORITY rename(String name) {
        return new JHI_AUTHORITY(name, null);
    }
}
