/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JHI_ENTITY_AUDIT_EVENT extends TableImpl<Record> {

    private static final long serialVersionUID = -1178494784;

    /**
     * The reference instance of <code>school.jhi_entity_audit_event</code>
     */
    public static final JHI_ENTITY_AUDIT_EVENT JHI_ENTITY_AUDIT_EVENT = new JHI_ENTITY_AUDIT_EVENT();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.jhi_entity_audit_event.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.jhi_entity_audit_event.action</code>.
     */
    public final TableField<Record, String> ACTION = createField("action", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>school.jhi_entity_audit_event.commit_version</code>.
     */
    public final TableField<Record, Integer> COMMIT_VERSION = createField("commit_version", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>school.jhi_entity_audit_event.entity_id</code>.
     */
    public final TableField<Record, Long> ENTITY_ID = createField("entity_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.jhi_entity_audit_event.entity_type</code>.
     */
    public final TableField<Record, String> ENTITY_TYPE = createField("entity_type", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>school.jhi_entity_audit_event.entity_value</code>.
     */
    public final TableField<Record, String> ENTITY_VALUE = createField("entity_value", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>school.jhi_entity_audit_event.modified_by</code>.
     */
    public final TableField<Record, String> MODIFIED_BY = createField("modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>school.jhi_entity_audit_event.modified_date</code>.
     */
    public final TableField<Record, Timestamp> MODIFIED_DATE = createField("modified_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>school.jhi_entity_audit_event</code> table reference
     */
    public JHI_ENTITY_AUDIT_EVENT() {
        this("jhi_entity_audit_event", null);
    }

    /**
     * Create an aliased <code>school.jhi_entity_audit_event</code> table reference
     */
    public JHI_ENTITY_AUDIT_EVENT(String alias) {
        this(alias, JHI_ENTITY_AUDIT_EVENT);
    }

    private JHI_ENTITY_AUDIT_EVENT(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private JHI_ENTITY_AUDIT_EVENT(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_JHI_ENTITY_AUDIT_EVENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_JHI_ENTITY_AUDIT_EVENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JHI_ENTITY_AUDIT_EVENT as(String alias) {
        return new JHI_ENTITY_AUDIT_EVENT(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JHI_ENTITY_AUDIT_EVENT rename(String name) {
        return new JHI_ENTITY_AUDIT_EVENT(name, null);
    }
}
