/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JHI_PERSISTENT_AUDIT_EVENT extends TableImpl<Record> {

    private static final long serialVersionUID = -1595607448;

    /**
     * The reference instance of <code>school.jhi_persistent_audit_event</code>
     */
    public static final JHI_PERSISTENT_AUDIT_EVENT JHI_PERSISTENT_AUDIT_EVENT = new JHI_PERSISTENT_AUDIT_EVENT();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.jhi_persistent_audit_event.event_id</code>.
     */
    public final TableField<Record, Long> EVENT_ID = createField("event_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.jhi_persistent_audit_event.event_date</code>.
     */
    public final TableField<Record, Timestamp> EVENT_DATE = createField("event_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.jhi_persistent_audit_event.event_type</code>.
     */
    public final TableField<Record, String> EVENT_TYPE = createField("event_type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.jhi_persistent_audit_event.principal</code>.
     */
    public final TableField<Record, String> PRINCIPAL = createField("principal", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>school.jhi_persistent_audit_event</code> table reference
     */
    public JHI_PERSISTENT_AUDIT_EVENT() {
        this("jhi_persistent_audit_event", null);
    }

    /**
     * Create an aliased <code>school.jhi_persistent_audit_event</code> table reference
     */
    public JHI_PERSISTENT_AUDIT_EVENT(String alias) {
        this(alias, JHI_PERSISTENT_AUDIT_EVENT);
    }

    private JHI_PERSISTENT_AUDIT_EVENT(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private JHI_PERSISTENT_AUDIT_EVENT(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_JHI_PERSISTENT_AUDIT_EVENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_JHI_PERSISTENT_AUDIT_EVENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_JHI_PERSISTENT_AUDIT_EVENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JHI_PERSISTENT_AUDIT_EVENT as(String alias) {
        return new JHI_PERSISTENT_AUDIT_EVENT(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JHI_PERSISTENT_AUDIT_EVENT rename(String name) {
        return new JHI_PERSISTENT_AUDIT_EVENT(name, null);
    }
}
