/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JHI_USER_AUTHORITY extends TableImpl<Record> {

    private static final long serialVersionUID = -94591232;

    /**
     * The reference instance of <code>school.jhi_user_authority</code>
     */
    public static final JHI_USER_AUTHORITY JHI_USER_AUTHORITY = new JHI_USER_AUTHORITY();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.jhi_user_authority.user_id</code>.
     */
    public final TableField<Record, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.jhi_user_authority.authority_name</code>.
     */
    public final TableField<Record, String> AUTHORITY_NAME = createField("authority_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * Create a <code>school.jhi_user_authority</code> table reference
     */
    public JHI_USER_AUTHORITY() {
        this("jhi_user_authority", null);
    }

    /**
     * Create an aliased <code>school.jhi_user_authority</code> table reference
     */
    public JHI_USER_AUTHORITY(String alias) {
        this(alias, JHI_USER_AUTHORITY);
    }

    private JHI_USER_AUTHORITY(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private JHI_USER_AUTHORITY(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_JHI_USER_AUTHORITY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_JHI_USER_AUTHORITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK290OKWW5JUJGHP4EL5I7MGWU0, Keys.FK4PSXL0JTX6NR7RHQBYNR6ITOC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JHI_USER_AUTHORITY as(String alias) {
        return new JHI_USER_AUTHORITY(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JHI_USER_AUTHORITY rename(String name) {
        return new JHI_USER_AUTHORITY(name, null);
    }
}
