/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JHI_USER extends TableImpl<Record> {

    private static final long serialVersionUID = 2023971264;

    /**
     * The reference instance of <code>school.jhi_user</code>
     */
    public static final JHI_USER JHI_USER = new JHI_USER();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.jhi_user.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.jhi_user.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.jhi_user.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.jhi_user.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.jhi_user.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.jhi_user.activated</code>.
     */
    public final TableField<Record, Boolean> ACTIVATED = createField("activated", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

    /**
     * The column <code>school.jhi_user.activation_key</code>.
     */
    public final TableField<Record, String> ACTIVATION_KEY = createField("activation_key", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>school.jhi_user.email</code>.
     */
    public final TableField<Record, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>school.jhi_user.first_name</code>.
     */
    public final TableField<Record, String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.jhi_user.image_url</code>.
     */
    public final TableField<Record, String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>school.jhi_user.lang_key</code>.
     */
    public final TableField<Record, String> LANG_KEY = createField("lang_key", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

    /**
     * The column <code>school.jhi_user.last_name</code>.
     */
    public final TableField<Record, String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.jhi_user.login</code>.
     */
    public final TableField<Record, String> LOGIN = createField("login", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.jhi_user.password_hash</code>.
     */
    public final TableField<Record, String> PASSWORD_HASH = createField("password_hash", org.jooq.impl.SQLDataType.VARCHAR.length(60).nullable(false), this, "");

    /**
     * The column <code>school.jhi_user.reset_date</code>.
     */
    public final TableField<Record, Timestamp> RESET_DATE = createField("reset_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.jhi_user.reset_key</code>.
     */
    public final TableField<Record, String> RESET_KEY = createField("reset_key", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * Create a <code>school.jhi_user</code> table reference
     */
    public JHI_USER() {
        this("jhi_user", null);
    }

    /**
     * Create an aliased <code>school.jhi_user</code> table reference
     */
    public JHI_USER(String alias) {
        this(alias, JHI_USER);
    }

    private JHI_USER(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private JHI_USER(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_JHI_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_JHI_USER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_JHI_USER_PRIMARY, Keys.KEY_JHI_USER_UK_BYCANYQUVI09Q7FH5PGXRQNKU, Keys.KEY_JHI_USER_UK_9Y0FRPQNMQE7Y6MK109VW3246);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JHI_USER as(String alias) {
        return new JHI_USER(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JHI_USER rename(String name) {
        return new JHI_USER(name, null);
    }
}
