/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LABOUR_SUMMARY extends TableImpl<Record> {

    private static final long serialVersionUID = 1554669114;

    /**
     * The reference instance of <code>school.labour_summary</code>
     */
    public static final LABOUR_SUMMARY LABOUR_SUMMARY = new LABOUR_SUMMARY();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.labour_summary.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.labour_summary.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.labour_summary.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.labour_summary.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.labour_summary.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.labour_summary.birth_place</code>.
     */
    public final TableField<Record, String> BIRTH_PLACE = createField("birth_place", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.labour_summary.labour</code>.
     */
    public final TableField<Record, String> LABOUR = createField("labour", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.labour_summary.membrane_ruptured</code>.
     */
    public final TableField<Record, String> MEMBRANE_RUPTURED = createField("membrane_ruptured", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.labour_summary.oxytocin_issued</code>.
     */
    public final TableField<Record, String> OXYTOCIN_ISSUED = createField("oxytocin_issued", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>school.labour_summary</code> table reference
     */
    public LABOUR_SUMMARY() {
        this("labour_summary", null);
    }

    /**
     * Create an aliased <code>school.labour_summary</code> table reference
     */
    public LABOUR_SUMMARY(String alias) {
        this(alias, LABOUR_SUMMARY);
    }

    private LABOUR_SUMMARY(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private LABOUR_SUMMARY(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_LABOUR_SUMMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_LABOUR_SUMMARY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_LABOUR_SUMMARY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LABOUR_SUMMARY as(String alias) {
        return new LABOUR_SUMMARY(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LABOUR_SUMMARY rename(String name) {
        return new LABOUR_SUMMARY(name, null);
    }
}
