/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NURSE_GENERAL_EXAMINATION extends TableImpl<Record> {

    private static final long serialVersionUID = 662627690;

    /**
     * The reference instance of <code>school.nurse_general_examination</code>
     */
    public static final NURSE_GENERAL_EXAMINATION NURSE_GENERAL_EXAMINATION = new NURSE_GENERAL_EXAMINATION();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.nurse_general_examination.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.nurse_general_examination.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.nurse_general_examination.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.nurse_general_examination.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.nurse_general_examination.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.nurse_general_examination.engagement</code>.
     */
    public final TableField<Record, String> ENGAGEMENT = createField("engagement", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.nurse_general_examination.lie</code>.
     */
    public final TableField<Record, String> LIE = createField("lie", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.nurse_general_examination.oedema</code>.
     */
    public final TableField<Record, Boolean> OEDEMA = createField("oedema", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>school.nurse_general_examination.presentation</code>.
     */
    public final TableField<Record, String> PRESENTATION = createField("presentation", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.nurse_general_examination.blood_pressure_id</code>.
     */
    public final TableField<Record, Long> BLOOD_PRESSURE_ID = createField("blood_pressure_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.nurse_general_examination.foetal_heart_rate_id</code>.
     */
    public final TableField<Record, Long> FOETAL_HEART_RATE_ID = createField("foetal_heart_rate_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.nurse_general_examination.haemoglobin_id</code>.
     */
    public final TableField<Record, Long> HAEMOGLOBIN_ID = createField("haemoglobin_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.nurse_general_examination.pulse_id</code>.
     */
    public final TableField<Record, Long> PULSE_ID = createField("pulse_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.nurse_general_examination.temperature_id</code>.
     */
    public final TableField<Record, Long> TEMPERATURE_ID = createField("temperature_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>school.nurse_general_examination</code> table reference
     */
    public NURSE_GENERAL_EXAMINATION() {
        this("nurse_general_examination", null);
    }

    /**
     * Create an aliased <code>school.nurse_general_examination</code> table reference
     */
    public NURSE_GENERAL_EXAMINATION(String alias) {
        this(alias, NURSE_GENERAL_EXAMINATION);
    }

    private NURSE_GENERAL_EXAMINATION(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private NURSE_GENERAL_EXAMINATION(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_NURSE_GENERAL_EXAMINATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_NURSE_GENERAL_EXAMINATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_NURSE_GENERAL_EXAMINATION_PRIMARY, Keys.KEY_NURSE_GENERAL_EXAMINATION_UK_FJRB7ERJGI5NX5HMKPIJLAV0P, Keys.KEY_NURSE_GENERAL_EXAMINATION_UK_5Y0RG11SP1B42AHD66973072F, Keys.KEY_NURSE_GENERAL_EXAMINATION_UK_N2E8SMKP4BU4FHTL44LTK7N7I, Keys.KEY_NURSE_GENERAL_EXAMINATION_UK_IYYYIULAN7TSV3LH2R9256UQ, Keys.KEY_NURSE_GENERAL_EXAMINATION_UK_HX4CTEX7OHA4RY4WI2SQWM9QO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FK7M5INA0O64OJSU43CWTLB1D9S, Keys.FK1L7PEO7FUMHDJ9L0E8HD8FEC1, Keys.FK9LWGTUGH6L6KKLY56076DSTE7, Keys.FKEJ0N0RAX0SEWRBWG8IVKKJ36K, Keys.FKTQR7MSXNRRK7ADAAHYXNU6CTB);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NURSE_GENERAL_EXAMINATION as(String alias) {
        return new NURSE_GENERAL_EXAMINATION(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public NURSE_GENERAL_EXAMINATION rename(String name) {
        return new NURSE_GENERAL_EXAMINATION(name, null);
    }
}
