/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OBSTRETRIC_EXAMINATION extends TableImpl<Record> {

    private static final long serialVersionUID = 1212015347;

    /**
     * The reference instance of <code>school.obstretric_examination</code>
     */
    public static final OBSTRETRIC_EXAMINATION OBSTRETRIC_EXAMINATION = new OBSTRETRIC_EXAMINATION();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.obstretric_examination.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.obstretric_examination.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.obstretric_examination.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.obstretric_examination.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.obstretric_examination.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>school.obstretric_examination</code> table reference
     */
    public OBSTRETRIC_EXAMINATION() {
        this("obstretric_examination", null);
    }

    /**
     * Create an aliased <code>school.obstretric_examination</code> table reference
     */
    public OBSTRETRIC_EXAMINATION(String alias) {
        this(alias, OBSTRETRIC_EXAMINATION);
    }

    private OBSTRETRIC_EXAMINATION(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private OBSTRETRIC_EXAMINATION(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_OBSTRETRIC_EXAMINATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_OBSTRETRIC_EXAMINATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_OBSTRETRIC_EXAMINATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OBSTRETRIC_EXAMINATION as(String alias) {
        return new OBSTRETRIC_EXAMINATION(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OBSTRETRIC_EXAMINATION rename(String name) {
        return new OBSTRETRIC_EXAMINATION(name, null);
    }
}
