/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OPD_ENCOUNTER extends TableImpl<Record> {

    private static final long serialVersionUID = -1915175301;

    /**
     * The reference instance of <code>school.opd_encounter</code>
     */
    public static final OPD_ENCOUNTER OPD_ENCOUNTER = new OPD_ENCOUNTER();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.opd_encounter.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.opd_encounter.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.opd_encounter.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.opd_encounter.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.opd_encounter.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.opd_encounter.encounter_id</code>.
     */
    public final TableField<Record, Long> ENCOUNTER_ID = createField("encounter_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.opd_encounter.opd_id</code>.
     */
    public final TableField<Record, Long> OPD_ID = createField("opd_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.opd_encounter</code> table reference
     */
    public OPD_ENCOUNTER() {
        this("opd_encounter", null);
    }

    /**
     * Create an aliased <code>school.opd_encounter</code> table reference
     */
    public OPD_ENCOUNTER(String alias) {
        this(alias, OPD_ENCOUNTER);
    }

    private OPD_ENCOUNTER(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private OPD_ENCOUNTER(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_OPD_ENCOUNTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_OPD_ENCOUNTER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_OPD_ENCOUNTER_PRIMARY, Keys.KEY_OPD_ENCOUNTER_UK_717T930WMTDJLT4O2L7NN3A9M);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKPFLQGBMPS0DLIN6ROCK7NB1P6, Keys.FKEOM0C2IO0FSVJ1IUJN9R9P5EY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OPD_ENCOUNTER as(String alias) {
        return new OPD_ENCOUNTER(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OPD_ENCOUNTER rename(String name) {
        return new OPD_ENCOUNTER(name, null);
    }
}
