/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PERSON_COMPLAINT extends TableImpl<Record> {

    private static final long serialVersionUID = -370012687;

    /**
     * The reference instance of <code>school.person_complaint</code>
     */
    public static final PERSON_COMPLAINT PERSON_COMPLAINT = new PERSON_COMPLAINT();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.person_complaint.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.person_complaint.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.person_complaint.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.person_complaint.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.person_complaint.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.person_complaint.date</code>.
     */
    public final TableField<Record, Date> DATE = createField("date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>school.person_complaint.duration</code>.
     */
    public final TableField<Record, Integer> DURATION = createField("duration", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>school.person_complaint.note</code>.
     */
    public final TableField<Record, String> NOTE = createField("note", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.person_complaint.present</code>.
     */
    public final TableField<Record, Boolean> PRESENT = createField("present", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

    /**
     * The column <code>school.person_complaint.complaint_id</code>.
     */
    public final TableField<Record, Long> COMPLAINT_ID = createField("complaint_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.person_complaint.person_id</code>.
     */
    public final TableField<Record, Long> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.person_complaint</code> table reference
     */
    public PERSON_COMPLAINT() {
        this("person_complaint", null);
    }

    /**
     * Create an aliased <code>school.person_complaint</code> table reference
     */
    public PERSON_COMPLAINT(String alias) {
        this(alias, PERSON_COMPLAINT);
    }

    private PERSON_COMPLAINT(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private PERSON_COMPLAINT(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_PERSON_COMPLAINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_PERSON_COMPLAINT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_PERSON_COMPLAINT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKIOS0XD9UFV0ST8IOQ7M7VM45L, Keys.FKNGQW90Q751WY6O7VC7DNJRD26);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PERSON_COMPLAINT as(String alias) {
        return new PERSON_COMPLAINT(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PERSON_COMPLAINT rename(String name) {
        return new PERSON_COMPLAINT(name, null);
    }
}
