/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PERSON_INVESTIGATION extends TableImpl<Record> {

    private static final long serialVersionUID = -611039255;

    /**
     * The reference instance of <code>school.person_investigation</code>
     */
    public static final PERSON_INVESTIGATION PERSON_INVESTIGATION = new PERSON_INVESTIGATION();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.person_investigation.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.person_investigation.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.person_investigation.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.person_investigation.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.person_investigation.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.person_investigation.date</code>.
     */
    public final TableField<Record, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.person_investigation.issue_date</code>.
     */
    public final TableField<Record, Date> ISSUE_DATE = createField("issue_date", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>school.person_investigation.result</code>.
     */
    public final TableField<Record, String> RESULT = createField("result", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.person_investigation.result_date</code>.
     */
    public final TableField<Record, Date> RESULT_DATE = createField("result_date", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>school.person_investigation.investigation_id</code>.
     */
    public final TableField<Record, Long> INVESTIGATION_ID = createField("investigation_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.person_investigation.person_id</code>.
     */
    public final TableField<Record, Long> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.person_investigation</code> table reference
     */
    public PERSON_INVESTIGATION() {
        this("person_investigation", null);
    }

    /**
     * Create an aliased <code>school.person_investigation</code> table reference
     */
    public PERSON_INVESTIGATION(String alias) {
        this(alias, PERSON_INVESTIGATION);
    }

    private PERSON_INVESTIGATION(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private PERSON_INVESTIGATION(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_PERSON_INVESTIGATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_PERSON_INVESTIGATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_PERSON_INVESTIGATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKP22JYPG544PWNVT4DD0X7G84J, Keys.FKEGU6SVD026SYWHYGFG1Q5L3L2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PERSON_INVESTIGATION as(String alias) {
        return new PERSON_INVESTIGATION(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PERSON_INVESTIGATION rename(String name) {
        return new PERSON_INVESTIGATION(name, null);
    }
}
