/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PERSON_ALLERGY extends TableImpl<Record> {

    private static final long serialVersionUID = 1226194960;

    /**
     * The reference instance of <code>school.person_allergy</code>
     */
    public static final PERSON_ALLERGY PERSON_ALLERGY = new PERSON_ALLERGY();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.person_allergy.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.person_allergy.allergy_id</code>.
     */
    public final TableField<Record, Long> ALLERGY_ID = createField("allergy_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.person_allergy.person_id</code>.
     */
    public final TableField<Record, Long> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.person_allergy</code> table reference
     */
    public PERSON_ALLERGY() {
        this("person_allergy", null);
    }

    /**
     * Create an aliased <code>school.person_allergy</code> table reference
     */
    public PERSON_ALLERGY(String alias) {
        this(alias, PERSON_ALLERGY);
    }

    private PERSON_ALLERGY(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private PERSON_ALLERGY(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_PERSON_ALLERGY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_PERSON_ALLERGY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_PERSON_ALLERGY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKBUXCBWW9MJVJWSO00UQHGI9H3, Keys.FKKSQEE62ICK5KKTMOJDWDM8SHK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PERSON_ALLERGY as(String alias) {
        return new PERSON_ALLERGY(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PERSON_ALLERGY rename(String name) {
        return new PERSON_ALLERGY(name, null);
    }
}
