/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PERSON_DIAGNOSIS extends TableImpl<Record> {

    private static final long serialVersionUID = -744034076;

    /**
     * The reference instance of <code>school.person_diagnosis</code>
     */
    public static final PERSON_DIAGNOSIS PERSON_DIAGNOSIS = new PERSON_DIAGNOSIS();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.person_diagnosis.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.person_diagnosis.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.person_diagnosis.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.person_diagnosis.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.person_diagnosis.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.person_diagnosis.date</code>.
     */
    public final TableField<Record, Date> DATE = createField("date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>school.person_diagnosis.definitive</code>.
     */
    public final TableField<Record, Boolean> DEFINITIVE = createField("definitive", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>school.person_diagnosis.differential</code>.
     */
    public final TableField<Record, Boolean> DIFFERENTIAL = createField("differential", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>school.person_diagnosis.final_diagnosis</code>.
     */
    public final TableField<Record, Boolean> FINAL_DIAGNOSIS = createField("final_diagnosis", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>school.person_diagnosis.working</code>.
     */
    public final TableField<Record, Boolean> WORKING = createField("working", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>school.person_diagnosis.diagnosis_id</code>.
     */
    public final TableField<Record, Long> DIAGNOSIS_ID = createField("diagnosis_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.person_diagnosis.person_id</code>.
     */
    public final TableField<Record, Long> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.person_diagnosis</code> table reference
     */
    public PERSON_DIAGNOSIS() {
        this("person_diagnosis", null);
    }

    /**
     * Create an aliased <code>school.person_diagnosis</code> table reference
     */
    public PERSON_DIAGNOSIS(String alias) {
        this(alias, PERSON_DIAGNOSIS);
    }

    private PERSON_DIAGNOSIS(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private PERSON_DIAGNOSIS(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_PERSON_DIAGNOSIS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_PERSON_DIAGNOSIS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_PERSON_DIAGNOSIS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKDO63SD54BKMDT7E8U3QORDHS6, Keys.FKNKTEN7XOPLAVJ4QR8IWVCHV87);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PERSON_DIAGNOSIS as(String alias) {
        return new PERSON_DIAGNOSIS(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PERSON_DIAGNOSIS rename(String name) {
        return new PERSON_DIAGNOSIS(name, null);
    }
}
