/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PERSON_HEALTH_EDUCATION extends TableImpl<Record> {

    private static final long serialVersionUID = -1893028407;

    /**
     * The reference instance of <code>school.person_health_education</code>
     */
    public static final PERSON_HEALTH_EDUCATION PERSON_HEALTH_EDUCATION = new PERSON_HEALTH_EDUCATION();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.person_health_education.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.person_health_education.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.person_health_education.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.person_health_education.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.person_health_education.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.person_health_education.date</code>.
     */
    public final TableField<Record, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.person_health_education.note</code>.
     */
    public final TableField<Record, String> NOTE = createField("note", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.person_health_education.type</code>.
     */
    public final TableField<Record, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.person_health_education.health_education_topic_id</code>.
     */
    public final TableField<Record, Long> HEALTH_EDUCATION_TOPIC_ID = createField("health_education_topic_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.person_health_education.person_id</code>.
     */
    public final TableField<Record, Long> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.person_health_education</code> table reference
     */
    public PERSON_HEALTH_EDUCATION() {
        this("person_health_education", null);
    }

    /**
     * Create an aliased <code>school.person_health_education</code> table reference
     */
    public PERSON_HEALTH_EDUCATION(String alias) {
        this(alias, PERSON_HEALTH_EDUCATION);
    }

    private PERSON_HEALTH_EDUCATION(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private PERSON_HEALTH_EDUCATION(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_PERSON_HEALTH_EDUCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_PERSON_HEALTH_EDUCATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_PERSON_HEALTH_EDUCATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKT4O3JT1DKGKH80ET68QVIPCVO, Keys.FKLPFLDEH9Y2D3M6I1P98J8VWT1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PERSON_HEALTH_EDUCATION as(String alias) {
        return new PERSON_HEALTH_EDUCATION(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PERSON_HEALTH_EDUCATION rename(String name) {
        return new PERSON_HEALTH_EDUCATION(name, null);
    }
}
