/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PERSON extends TableImpl<Record> {

    private static final long serialVersionUID = -1610492432;

    /**
     * The reference instance of <code>school.person</code>
     */
    public static final PERSON PERSON = new PERSON();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.person.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.person.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.person.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.person.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.person.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.person.birthdate</code>.
     */
    public final TableField<Record, Date> BIRTHDATE = createField("birthdate", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>school.person.firstname</code>.
     */
    public final TableField<Record, String> FIRSTNAME = createField("firstname", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>school.person.estimate_age</code>.
     */
    public final TableField<Record, Boolean> ESTIMATE_AGE = createField("estimate_age", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>school.person.lastname</code>.
     */
    public final TableField<Record, String> LASTNAME = createField("lastname", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>school.person.sex</code>.
     */
    public final TableField<Record, String> SEX = createField("sex", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>school.person.education_level_id</code>.
     */
    public final TableField<Record, Long> EDUCATION_LEVEL_ID = createField("education_level_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.person.marital_state_id</code>.
     */
    public final TableField<Record, Long> MARITAL_STATE_ID = createField("marital_state_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.person.occupation_id</code>.
     */
    public final TableField<Record, Long> OCCUPATION_ID = createField("occupation_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>school.person</code> table reference
     */
    public PERSON() {
        this("person", null);
    }

    /**
     * Create an aliased <code>school.person</code> table reference
     */
    public PERSON(String alias) {
        this(alias, PERSON);
    }

    private PERSON(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private PERSON(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_PERSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_PERSON_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_PERSON_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKIAJYEJYT0PRRSR89OG50O7E0U, Keys.FK9WWVOOQH48NBDBOI6SH07RWFF, Keys.FKDP9RUV0ECVE41WP6B6BJSHUWD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PERSON as(String alias) {
        return new PERSON(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PERSON rename(String name) {
        return new PERSON(name, null);
    }
}
