/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PLACENTA_AND_MEMBRANE extends TableImpl<Record> {

    private static final long serialVersionUID = -86731438;

    /**
     * The reference instance of <code>school.placenta_and_membrane</code>
     */
    public static final PLACENTA_AND_MEMBRANE PLACENTA_AND_MEMBRANE = new PLACENTA_AND_MEMBRANE();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.placenta_and_membrane.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.placenta_and_membrane.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.placenta_and_membrane.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.placenta_and_membrane.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.placenta_and_membrane.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.placenta_and_membrane.date</code>.
     */
    public final TableField<Record, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.placenta_and_membrane.delivery_method</code>.
     */
    public final TableField<Record, String> DELIVERY_METHOD = createField("delivery_method", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.placenta_and_membrane.membrane_description</code>.
     */
    public final TableField<Record, String> MEMBRANE_DESCRIPTION = createField("membrane_description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.placenta_and_membrane.membrane_state</code>.
     */
    public final TableField<Record, String> MEMBRANE_STATE = createField("membrane_state", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.placenta_and_membrane.placenta_description</code>.
     */
    public final TableField<Record, String> PLACENTA_DESCRIPTION = createField("placenta_description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.placenta_and_membrane.placenta_state</code>.
     */
    public final TableField<Record, String> PLACENTA_STATE = createField("placenta_state", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.placenta_and_membrane.placenta_weight</code>.
     */
    public final TableField<Record, Long> PLACENTA_WEIGHT = createField("placenta_weight", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>school.placenta_and_membrane.umbilical_cord_description</code>.
     */
    public final TableField<Record, String> UMBILICAL_CORD_DESCRIPTION = createField("umbilical_cord_description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.placenta_and_membrane.umbilical_cord_state</code>.
     */
    public final TableField<Record, String> UMBILICAL_CORD_STATE = createField("umbilical_cord_state", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>school.placenta_and_membrane.umbilical_cord_vessel</code>.
     */
    public final TableField<Record, Integer> UMBILICAL_CORD_VESSEL = createField("umbilical_cord_vessel", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>school.placenta_and_membrane</code> table reference
     */
    public PLACENTA_AND_MEMBRANE() {
        this("placenta_and_membrane", null);
    }

    /**
     * Create an aliased <code>school.placenta_and_membrane</code> table reference
     */
    public PLACENTA_AND_MEMBRANE(String alias) {
        this(alias, PLACENTA_AND_MEMBRANE);
    }

    private PLACENTA_AND_MEMBRANE(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private PLACENTA_AND_MEMBRANE(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_PLACENTA_AND_MEMBRANE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_PLACENTA_AND_MEMBRANE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_PLACENTA_AND_MEMBRANE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PLACENTA_AND_MEMBRANE as(String alias) {
        return new PLACENTA_AND_MEMBRANE(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PLACENTA_AND_MEMBRANE rename(String name) {
        return new PLACENTA_AND_MEMBRANE(name, null);
    }
}
