/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import zw.co.elearning.school.db.Keys;
import zw.co.elearning.school.db.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZEPI_DRUG_NAME extends TableImpl<Record> {

    private static final long serialVersionUID = 1564007116;

    /**
     * The reference instance of <code>school.zepi_drug_name</code>
     */
    public static final ZEPI_DRUG_NAME ZEPI_DRUG_NAME = new ZEPI_DRUG_NAME();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>school.zepi_drug_name.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>school.zepi_drug_name.created_by</code>.
     */
    public final TableField<Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>school.zepi_drug_name.created_date</code>.
     */
    public final TableField<Record, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>school.zepi_drug_name.last_modified_by</code>.
     */
    public final TableField<Record, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>school.zepi_drug_name.last_modified_date</code>.
     */
    public final TableField<Record, Timestamp> LAST_MODIFIED_DATE = createField("last_modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>school.zepi_drug_name.discontinued</code>.
     */
    public final TableField<Record, Boolean> DISCONTINUED = createField("discontinued", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>school.zepi_drug_name.drug_name_id</code>.
     */
    public final TableField<Record, Long> DRUG_NAME_ID = createField("drug_name_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>school.zepi_drug_name</code> table reference
     */
    public ZEPI_DRUG_NAME() {
        this("zepi_drug_name", null);
    }

    /**
     * Create an aliased <code>school.zepi_drug_name</code> table reference
     */
    public ZEPI_DRUG_NAME(String alias) {
        this(alias, ZEPI_DRUG_NAME);
    }

    private ZEPI_DRUG_NAME(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ZEPI_DRUG_NAME(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return School.SCHOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_ZEPI_DRUG_NAME_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_ZEPI_DRUG_NAME_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.FKFOHAC1FEKPYC3EXJLP49V8WAH);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ZEPI_DRUG_NAME as(String alias) {
        return new ZEPI_DRUG_NAME(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ZEPI_DRUG_NAME rename(String name) {
        return new ZEPI_DRUG_NAME(name, null);
    }
}
