/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import zw.co.elearning.school.db.tables.ADDRESS;
import zw.co.elearning.school.db.tables.ADMISSION;
import zw.co.elearning.school.db.tables.ADMISSION_ENCOUNTER;
import zw.co.elearning.school.db.tables.ALLERGY;
import zw.co.elearning.school.db.tables.AMNIOTIC_FLUID;
import zw.co.elearning.school.db.tables.ANC;
import zw.co.elearning.school.db.tables.ANC_HISTORY;
import zw.co.elearning.school.db.tables.ANC_QUESTIONARE;
import zw.co.elearning.school.db.tables.ANC_VISIT;
import zw.co.elearning.school.db.tables.APPOINTMENT;
import zw.co.elearning.school.db.tables.APPOINTMENT_CANCELLATION_REASON;
import zw.co.elearning.school.db.tables.APPOINTMENT_REASON;
import zw.co.elearning.school.db.tables.APPOINTMENT_RESCHEDULLING_REASON;
import zw.co.elearning.school.db.tables.ART;
import zw.co.elearning.school.db.tables.ART_CURRENT_SIGN;
import zw.co.elearning.school.db.tables.ART_CURRENT_SYMPTOM;
import zw.co.elearning.school.db.tables.ART_INVESTIGATION_HISTORY;
import zw.co.elearning.school.db.tables.ART_MEDICAL_HISTORY;
import zw.co.elearning.school.db.tables.ART_MEDICATION_HISTORY;
import zw.co.elearning.school.db.tables.ART_QUESTIONARE;
import zw.co.elearning.school.db.tables.ART_REASON;
import zw.co.elearning.school.db.tables.ART_STATUS;
import zw.co.elearning.school.db.tables.ART_VISIT;
import zw.co.elearning.school.db.tables.ART_VISIT_NEW_OI;
import zw.co.elearning.school.db.tables.ART_VISIT_STATUS;
import zw.co.elearning.school.db.tables.ART_VISIT_TYPE;
import zw.co.elearning.school.db.tables.ARV_COMBINATION_REGIMEN;
import zw.co.elearning.school.db.tables.CERVIX;
import zw.co.elearning.school.db.tables.COMPLAINT;
import zw.co.elearning.school.db.tables.CONTRACTION;
import zw.co.elearning.school.db.tables.DEGREE;
import zw.co.elearning.school.db.tables.DEGREE_OF_MOULDING;
import zw.co.elearning.school.db.tables.DELIVERY;
import zw.co.elearning.school.db.tables.DELIVERY_HISTORY;
import zw.co.elearning.school.db.tables.DELIVERY_MATERNAL_DEATH_FACTOR;
import zw.co.elearning.school.db.tables.DELIVERY_PARTOGRAM;
import zw.co.elearning.school.db.tables.DELIVERY_QUESTIONARE;
import zw.co.elearning.school.db.tables.DELIVERY_SUMMARY;
import zw.co.elearning.school.db.tables.DELIVERY_TYPE;
import zw.co.elearning.school.db.tables.DEPARTMENT;
import zw.co.elearning.school.db.tables.DIAGNOSIS;
import zw.co.elearning.school.db.tables.DISPENSE;
import zw.co.elearning.school.db.tables.DISTRICT;
import zw.co.elearning.school.db.tables.DOCTOR_GENERAL_EXAMINATION;
import zw.co.elearning.school.db.tables.DOCTOR_VAGINAL_EXAMINATION;
import zw.co.elearning.school.db.tables.DRUG;
import zw.co.elearning.school.db.tables.DRUG_BATCH;
import zw.co.elearning.school.db.tables.DRUG_NAME;
import zw.co.elearning.school.db.tables.DRUG_OPTION;
import zw.co.elearning.school.db.tables.DRUG_SUFFIX;
import zw.co.elearning.school.db.tables.EDUCATION_LEVEL;
import zw.co.elearning.school.db.tables.EMAIL;
import zw.co.elearning.school.db.tables.ENCOUNTER;
import zw.co.elearning.school.db.tables.ENCOUNTER_COMPLAINT;
import zw.co.elearning.school.db.tables.ENCOUNTER_DIAGNOSIS;
import zw.co.elearning.school.db.tables.ENCOUNTER_EXAMINATION;
import zw.co.elearning.school.db.tables.ENCOUNTER_HEALTH_EDUCATION;
import zw.co.elearning.school.db.tables.ENCOUNTER_INVESTIGATION;
import zw.co.elearning.school.db.tables.ENCOUNTER_MEDICATION;
import zw.co.elearning.school.db.tables.ENCOUNTER_NOTE;
import zw.co.elearning.school.db.tables.ENCOUNTER_PROCEDURE;
import zw.co.elearning.school.db.tables.ENCOUNTER_VITAL;
import zw.co.elearning.school.db.tables.EXAMINATION;
import zw.co.elearning.school.db.tables.FACILITY;
import zw.co.elearning.school.db.tables.FAMILY_PLANNING_METHOD;
import zw.co.elearning.school.db.tables.FEEDING_OPTION;
import zw.co.elearning.school.db.tables.FOETAL_DEATH;
import zw.co.elearning.school.db.tables.FOLLOW_UP_STATUS;
import zw.co.elearning.school.db.tables.FORMULATION;
import zw.co.elearning.school.db.tables.FREQUENCY;
import zw.co.elearning.school.db.tables.FUNCTIONAL_STATUS;
import zw.co.elearning.school.db.tables.GENERAL_ASSESSMENT;
import zw.co.elearning.school.db.tables.HEALTH_EDUCATION_TOPIC;
import zw.co.elearning.school.db.tables.HIBERNATE_SEQUENCE;
import zw.co.elearning.school.db.tables.HTS;
import zw.co.elearning.school.db.tables.HTS_MODEL;
import zw.co.elearning.school.db.tables.HTS_POST_TEST_SERVICE;
import zw.co.elearning.school.db.tables.HTS_POST_TEST_SERVICE_OFFERED;
import zw.co.elearning.school.db.tables.IMMUNIZATION_SCHEDULE;
import zw.co.elearning.school.db.tables.IMNCI_CATEGORY;
import zw.co.elearning.school.db.tables.IMNCI_CLASSIFICATION;
import zw.co.elearning.school.db.tables.IMNCI_QUESTIONNAIRE;
import zw.co.elearning.school.db.tables.IMNCI_VISIT;
import zw.co.elearning.school.db.tables.IMNCI_VISIT_QUESTION;
import zw.co.elearning.school.db.tables.INFANT;
import zw.co.elearning.school.db.tables.INVESTIGATION;
import zw.co.elearning.school.db.tables.INVESTIGATION_HISTORY;
import zw.co.elearning.school.db.tables.INVESTIGATION_RESULT;
import zw.co.elearning.school.db.tables.INVESTIGATION_RESULT_DIAGNOSES;
import zw.co.elearning.school.db.tables.INVESTIGATION_TEST_KIT;
import zw.co.elearning.school.db.tables.IPT_REASON;
import zw.co.elearning.school.db.tables.IPT_STATUS;
import zw.co.elearning.school.db.tables.JHI_AUTHORITY;
import zw.co.elearning.school.db.tables.JHI_ENTITY_AUDIT_EVENT;
import zw.co.elearning.school.db.tables.JHI_PERSISTENT_AUDIT_EVENT;
import zw.co.elearning.school.db.tables.JHI_PERSISTENT_AUDIT_EVT_DATA;
import zw.co.elearning.school.db.tables.JHI_USER;
import zw.co.elearning.school.db.tables.JHI_USER_AUTHORITY;
import zw.co.elearning.school.db.tables.LABORATORY;
import zw.co.elearning.school.db.tables.LABOUR_SUMMARY;
import zw.co.elearning.school.db.tables.LAB_RESULT;
import zw.co.elearning.school.db.tables.LAB_TEST;
import zw.co.elearning.school.db.tables.LEVEL_OF_PRESENTING_PART;
import zw.co.elearning.school.db.tables.MARITAL_STATE;
import zw.co.elearning.school.db.tables.MATERNAL_DEATH;
import zw.co.elearning.school.db.tables.MATERNAL_DEATH_FACTOR;
import zw.co.elearning.school.db.tables.MEDICAL_AID;
import zw.co.elearning.school.db.tables.MEDICAL_AID_PROVIDER;
import zw.co.elearning.school.db.tables.MEDICAL_PROCEDURE;
import zw.co.elearning.school.db.tables.NURSE_GENERAL_EXAMINATION;
import zw.co.elearning.school.db.tables.NURSE_VAGINAL_EXAMINATION;
import zw.co.elearning.school.db.tables.OBSTETRIC_EXAMINATION;
import zw.co.elearning.school.db.tables.OBSTRETRIC_EXAMINATION;
import zw.co.elearning.school.db.tables.OCCUPATION;
import zw.co.elearning.school.db.tables.OPD;
import zw.co.elearning.school.db.tables.OPD_ENCOUNTER;
import zw.co.elearning.school.db.tables.OPD_QUEUE;
import zw.co.elearning.school.db.tables.PERINIUM_REPAIR_TYPE;
import zw.co.elearning.school.db.tables.PERSON;
import zw.co.elearning.school.db.tables.PERSON_ALLERGY;
import zw.co.elearning.school.db.tables.PERSON_ART_FOLLOW_UP_STATUS;
import zw.co.elearning.school.db.tables.PERSON_ART_FUNCTIONAL_STATUS;
import zw.co.elearning.school.db.tables.PERSON_ART_IPT_STATUS;
import zw.co.elearning.school.db.tables.PERSON_ART_REGIMEN;
import zw.co.elearning.school.db.tables.PERSON_ART_STATUS;
import zw.co.elearning.school.db.tables.PERSON_ART_WHO_STAGE;
import zw.co.elearning.school.db.tables.PERSON_COMPLAINT;
import zw.co.elearning.school.db.tables.PERSON_DIAGNOSIS;
import zw.co.elearning.school.db.tables.PERSON_EXAMINATION;
import zw.co.elearning.school.db.tables.PERSON_HEALTH_EDUCATION;
import zw.co.elearning.school.db.tables.PERSON_ID;
import zw.co.elearning.school.db.tables.PERSON_IDENTIFIER;
import zw.co.elearning.school.db.tables.PERSON_INVESTIGATION;
import zw.co.elearning.school.db.tables.PERSON_INVESTIGATION_TEST;
import zw.co.elearning.school.db.tables.PERSON_MEDICATION;
import zw.co.elearning.school.db.tables.PERSON_PROCEDURE;
import zw.co.elearning.school.db.tables.PERSON_VITAL;
import zw.co.elearning.school.db.tables.PHONE;
import zw.co.elearning.school.db.tables.PLACENTA_AND_MEMBRANE;
import zw.co.elearning.school.db.tables.PLACENTA_DELIVERY_TYPE;
import zw.co.elearning.school.db.tables.PNC;
import zw.co.elearning.school.db.tables.PNC_CHILD;
import zw.co.elearning.school.db.tables.PNC_PROPERTY;
import zw.co.elearning.school.db.tables.PNC_QUESTIONARE;
import zw.co.elearning.school.db.tables.PNC_QUESTIONARE_CATEGORY;
import zw.co.elearning.school.db.tables.PNC_VISIT;
import zw.co.elearning.school.db.tables.PNC_VISIT_TYPE;
import zw.co.elearning.school.db.tables.PRESCRIPTION;
import zw.co.elearning.school.db.tables.PROVINCE;
import zw.co.elearning.school.db.tables.PURPOSE_OF_TEST;
import zw.co.elearning.school.db.tables.QUEUE;
import zw.co.elearning.school.db.tables.REASON_FOR_NOT_ISSUING_RESULT;
import zw.co.elearning.school.db.tables.REFERRAL;
import zw.co.elearning.school.db.tables.REFERRAL_REASON;
import zw.co.elearning.school.db.tables.RELATION;
import zw.co.elearning.school.db.tables.RELATIONSHIP_TYPE;
import zw.co.elearning.school.db.tables.SAMPLE;
import zw.co.elearning.school.db.tables.SITE_SETTING;
import zw.co.elearning.school.db.tables.STAGE;
import zw.co.elearning.school.db.tables.STAGE_NUMBER;
import zw.co.elearning.school.db.tables.STANDARD;
import zw.co.elearning.school.db.tables.SUPPLIER;
import zw.co.elearning.school.db.tables.TB;
import zw.co.elearning.school.db.tables.TB_CATEGORY;
import zw.co.elearning.school.db.tables.TB_QUESTIONARE;
import zw.co.elearning.school.db.tables.TB_RISK_GROUP;
import zw.co.elearning.school.db.tables.TB_STATUS;
import zw.co.elearning.school.db.tables.TB_SURVEY;
import zw.co.elearning.school.db.tables.TB_VISIT;
import zw.co.elearning.school.db.tables.TEST_KIT;
import zw.co.elearning.school.db.tables.TEST_KIT_BATCH;
import zw.co.elearning.school.db.tables.TOWN;
import zw.co.elearning.school.db.tables.UNIT;
import zw.co.elearning.school.db.tables.VAGINAL_MONITORING;
import zw.co.elearning.school.db.tables.VITAL;
import zw.co.elearning.school.db.tables.WARD;
import zw.co.elearning.school.db.tables.ZEPI_DRUG_NAME;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class School extends SchemaImpl {

    private static final long serialVersionUID = -1721633591;

    /**
     * The reference instance of <code>school</code>
     */
    public static final School SCHOOL = new School();

    /**
     * The table <code>school.address</code>.
     */
    public final ADDRESS ADDRESS = zw.co.elearning.school.db.tables.ADDRESS.ADDRESS;

    /**
     * The table <code>school.admission</code>.
     */
    public final ADMISSION ADMISSION = zw.co.elearning.school.db.tables.ADMISSION.ADMISSION;

    /**
     * The table <code>school.admission_encounter</code>.
     */
    public final ADMISSION_ENCOUNTER ADMISSION_ENCOUNTER = zw.co.elearning.school.db.tables.ADMISSION_ENCOUNTER.ADMISSION_ENCOUNTER;

    /**
     * The table <code>school.allergy</code>.
     */
    public final ALLERGY ALLERGY = zw.co.elearning.school.db.tables.ALLERGY.ALLERGY;

    /**
     * The table <code>school.amniotic_fluid</code>.
     */
    public final AMNIOTIC_FLUID AMNIOTIC_FLUID = zw.co.elearning.school.db.tables.AMNIOTIC_FLUID.AMNIOTIC_FLUID;

    /**
     * The table <code>school.anc</code>.
     */
    public final ANC ANC = zw.co.elearning.school.db.tables.ANC.ANC;

    /**
     * The table <code>school.anc_history</code>.
     */
    public final ANC_HISTORY ANC_HISTORY = zw.co.elearning.school.db.tables.ANC_HISTORY.ANC_HISTORY;

    /**
     * The table <code>school.anc_questionare</code>.
     */
    public final ANC_QUESTIONARE ANC_QUESTIONARE = zw.co.elearning.school.db.tables.ANC_QUESTIONARE.ANC_QUESTIONARE;

    /**
     * The table <code>school.anc_visit</code>.
     */
    public final ANC_VISIT ANC_VISIT = zw.co.elearning.school.db.tables.ANC_VISIT.ANC_VISIT;

    /**
     * The table <code>school.appointment</code>.
     */
    public final APPOINTMENT APPOINTMENT = zw.co.elearning.school.db.tables.APPOINTMENT.APPOINTMENT;

    /**
     * The table <code>school.appointment_cancellation_reason</code>.
     */
    public final APPOINTMENT_CANCELLATION_REASON APPOINTMENT_CANCELLATION_REASON = zw.co.elearning.school.db.tables.APPOINTMENT_CANCELLATION_REASON.APPOINTMENT_CANCELLATION_REASON;

    /**
     * The table <code>school.appointment_reason</code>.
     */
    public final APPOINTMENT_REASON APPOINTMENT_REASON = zw.co.elearning.school.db.tables.APPOINTMENT_REASON.APPOINTMENT_REASON;

    /**
     * The table <code>school.appointment_reschedulling_reason</code>.
     */
    public final APPOINTMENT_RESCHEDULLING_REASON APPOINTMENT_RESCHEDULLING_REASON = zw.co.elearning.school.db.tables.APPOINTMENT_RESCHEDULLING_REASON.APPOINTMENT_RESCHEDULLING_REASON;

    /**
     * The table <code>school.art</code>.
     */
    public final ART ART = zw.co.elearning.school.db.tables.ART.ART;

    /**
     * The table <code>school.art_current_sign</code>.
     */
    public final ART_CURRENT_SIGN ART_CURRENT_SIGN = zw.co.elearning.school.db.tables.ART_CURRENT_SIGN.ART_CURRENT_SIGN;

    /**
     * The table <code>school.art_current_symptom</code>.
     */
    public final ART_CURRENT_SYMPTOM ART_CURRENT_SYMPTOM = zw.co.elearning.school.db.tables.ART_CURRENT_SYMPTOM.ART_CURRENT_SYMPTOM;

    /**
     * The table <code>school.art_investigation_history</code>.
     */
    public final ART_INVESTIGATION_HISTORY ART_INVESTIGATION_HISTORY = zw.co.elearning.school.db.tables.ART_INVESTIGATION_HISTORY.ART_INVESTIGATION_HISTORY;

    /**
     * The table <code>school.art_medical_history</code>.
     */
    public final ART_MEDICAL_HISTORY ART_MEDICAL_HISTORY = zw.co.elearning.school.db.tables.ART_MEDICAL_HISTORY.ART_MEDICAL_HISTORY;

    /**
     * The table <code>school.art_medication_history</code>.
     */
    public final ART_MEDICATION_HISTORY ART_MEDICATION_HISTORY = zw.co.elearning.school.db.tables.ART_MEDICATION_HISTORY.ART_MEDICATION_HISTORY;

    /**
     * The table <code>school.art_questionare</code>.
     */
    public final ART_QUESTIONARE ART_QUESTIONARE = zw.co.elearning.school.db.tables.ART_QUESTIONARE.ART_QUESTIONARE;

    /**
     * The table <code>school.art_reason</code>.
     */
    public final ART_REASON ART_REASON = zw.co.elearning.school.db.tables.ART_REASON.ART_REASON;

    /**
     * The table <code>school.art_status</code>.
     */
    public final ART_STATUS ART_STATUS = zw.co.elearning.school.db.tables.ART_STATUS.ART_STATUS;

    /**
     * The table <code>school.art_visit</code>.
     */
    public final ART_VISIT ART_VISIT = zw.co.elearning.school.db.tables.ART_VISIT.ART_VISIT;

    /**
     * The table <code>school.art_visit_new_oi</code>.
     */
    public final ART_VISIT_NEW_OI ART_VISIT_NEW_OI = zw.co.elearning.school.db.tables.ART_VISIT_NEW_OI.ART_VISIT_NEW_OI;

    /**
     * The table <code>school.art_visit_status</code>.
     */
    public final ART_VISIT_STATUS ART_VISIT_STATUS = zw.co.elearning.school.db.tables.ART_VISIT_STATUS.ART_VISIT_STATUS;

    /**
     * The table <code>school.art_visit_type</code>.
     */
    public final ART_VISIT_TYPE ART_VISIT_TYPE = zw.co.elearning.school.db.tables.ART_VISIT_TYPE.ART_VISIT_TYPE;

    /**
     * The table <code>school.arv_combination_regimen</code>.
     */
    public final ARV_COMBINATION_REGIMEN ARV_COMBINATION_REGIMEN = zw.co.elearning.school.db.tables.ARV_COMBINATION_REGIMEN.ARV_COMBINATION_REGIMEN;

    /**
     * The table <code>school.cervix</code>.
     */
    public final CERVIX CERVIX = zw.co.elearning.school.db.tables.CERVIX.CERVIX;

    /**
     * The table <code>school.complaint</code>.
     */
    public final COMPLAINT COMPLAINT = zw.co.elearning.school.db.tables.COMPLAINT.COMPLAINT;

    /**
     * The table <code>school.contraction</code>.
     */
    public final CONTRACTION CONTRACTION = zw.co.elearning.school.db.tables.CONTRACTION.CONTRACTION;

    /**
     * The table <code>school.degree</code>.
     */
    public final DEGREE DEGREE = zw.co.elearning.school.db.tables.DEGREE.DEGREE;

    /**
     * The table <code>school.degree_of_moulding</code>.
     */
    public final DEGREE_OF_MOULDING DEGREE_OF_MOULDING = zw.co.elearning.school.db.tables.DEGREE_OF_MOULDING.DEGREE_OF_MOULDING;

    /**
     * The table <code>school.delivery</code>.
     */
    public final DELIVERY DELIVERY = zw.co.elearning.school.db.tables.DELIVERY.DELIVERY;

    /**
     * The table <code>school.delivery_history</code>.
     */
    public final DELIVERY_HISTORY DELIVERY_HISTORY = zw.co.elearning.school.db.tables.DELIVERY_HISTORY.DELIVERY_HISTORY;

    /**
     * The table <code>school.delivery_maternal_death_factor</code>.
     */
    public final DELIVERY_MATERNAL_DEATH_FACTOR DELIVERY_MATERNAL_DEATH_FACTOR = zw.co.elearning.school.db.tables.DELIVERY_MATERNAL_DEATH_FACTOR.DELIVERY_MATERNAL_DEATH_FACTOR;

    /**
     * The table <code>school.delivery_partogram</code>.
     */
    public final DELIVERY_PARTOGRAM DELIVERY_PARTOGRAM = zw.co.elearning.school.db.tables.DELIVERY_PARTOGRAM.DELIVERY_PARTOGRAM;

    /**
     * The table <code>school.delivery_questionare</code>.
     */
    public final DELIVERY_QUESTIONARE DELIVERY_QUESTIONARE = zw.co.elearning.school.db.tables.DELIVERY_QUESTIONARE.DELIVERY_QUESTIONARE;

    /**
     * The table <code>school.delivery_summary</code>.
     */
    public final DELIVERY_SUMMARY DELIVERY_SUMMARY = zw.co.elearning.school.db.tables.DELIVERY_SUMMARY.DELIVERY_SUMMARY;

    /**
     * The table <code>school.delivery_type</code>.
     */
    public final DELIVERY_TYPE DELIVERY_TYPE = zw.co.elearning.school.db.tables.DELIVERY_TYPE.DELIVERY_TYPE;

    /**
     * The table <code>school.department</code>.
     */
    public final DEPARTMENT DEPARTMENT = zw.co.elearning.school.db.tables.DEPARTMENT.DEPARTMENT;

    /**
     * The table <code>school.diagnosis</code>.
     */
    public final DIAGNOSIS DIAGNOSIS = zw.co.elearning.school.db.tables.DIAGNOSIS.DIAGNOSIS;

    /**
     * The table <code>school.dispense</code>.
     */
    public final DISPENSE DISPENSE = zw.co.elearning.school.db.tables.DISPENSE.DISPENSE;

    /**
     * The table <code>school.district</code>.
     */
    public final DISTRICT DISTRICT = zw.co.elearning.school.db.tables.DISTRICT.DISTRICT;

    /**
     * The table <code>school.doctor_general_examination</code>.
     */
    public final DOCTOR_GENERAL_EXAMINATION DOCTOR_GENERAL_EXAMINATION = zw.co.elearning.school.db.tables.DOCTOR_GENERAL_EXAMINATION.DOCTOR_GENERAL_EXAMINATION;

    /**
     * The table <code>school.doctor_vaginal_examination</code>.
     */
    public final DOCTOR_VAGINAL_EXAMINATION DOCTOR_VAGINAL_EXAMINATION = zw.co.elearning.school.db.tables.DOCTOR_VAGINAL_EXAMINATION.DOCTOR_VAGINAL_EXAMINATION;

    /**
     * The table <code>school.drug</code>.
     */
    public final DRUG DRUG = zw.co.elearning.school.db.tables.DRUG.DRUG;

    /**
     * The table <code>school.drug_batch</code>.
     */
    public final DRUG_BATCH DRUG_BATCH = zw.co.elearning.school.db.tables.DRUG_BATCH.DRUG_BATCH;

    /**
     * The table <code>school.drug_name</code>.
     */
    public final DRUG_NAME DRUG_NAME = zw.co.elearning.school.db.tables.DRUG_NAME.DRUG_NAME;

    /**
     * The table <code>school.drug_option</code>.
     */
    public final DRUG_OPTION DRUG_OPTION = zw.co.elearning.school.db.tables.DRUG_OPTION.DRUG_OPTION;

    /**
     * The table <code>school.drug_suffix</code>.
     */
    public final DRUG_SUFFIX DRUG_SUFFIX = zw.co.elearning.school.db.tables.DRUG_SUFFIX.DRUG_SUFFIX;

    /**
     * The table <code>school.education_level</code>.
     */
    public final EDUCATION_LEVEL EDUCATION_LEVEL = zw.co.elearning.school.db.tables.EDUCATION_LEVEL.EDUCATION_LEVEL;

    /**
     * The table <code>school.email</code>.
     */
    public final EMAIL EMAIL = zw.co.elearning.school.db.tables.EMAIL.EMAIL;

    /**
     * The table <code>school.encounter</code>.
     */
    public final ENCOUNTER ENCOUNTER = zw.co.elearning.school.db.tables.ENCOUNTER.ENCOUNTER;

    /**
     * The table <code>school.encounter_complaint</code>.
     */
    public final ENCOUNTER_COMPLAINT ENCOUNTER_COMPLAINT = zw.co.elearning.school.db.tables.ENCOUNTER_COMPLAINT.ENCOUNTER_COMPLAINT;

    /**
     * The table <code>school.encounter_diagnosis</code>.
     */
    public final ENCOUNTER_DIAGNOSIS ENCOUNTER_DIAGNOSIS = zw.co.elearning.school.db.tables.ENCOUNTER_DIAGNOSIS.ENCOUNTER_DIAGNOSIS;

    /**
     * The table <code>school.encounter_examination</code>.
     */
    public final ENCOUNTER_EXAMINATION ENCOUNTER_EXAMINATION = zw.co.elearning.school.db.tables.ENCOUNTER_EXAMINATION.ENCOUNTER_EXAMINATION;

    /**
     * The table <code>school.encounter_health_education</code>.
     */
    public final ENCOUNTER_HEALTH_EDUCATION ENCOUNTER_HEALTH_EDUCATION = zw.co.elearning.school.db.tables.ENCOUNTER_HEALTH_EDUCATION.ENCOUNTER_HEALTH_EDUCATION;

    /**
     * The table <code>school.encounter_investigation</code>.
     */
    public final ENCOUNTER_INVESTIGATION ENCOUNTER_INVESTIGATION = zw.co.elearning.school.db.tables.ENCOUNTER_INVESTIGATION.ENCOUNTER_INVESTIGATION;

    /**
     * The table <code>school.encounter_medication</code>.
     */
    public final ENCOUNTER_MEDICATION ENCOUNTER_MEDICATION = zw.co.elearning.school.db.tables.ENCOUNTER_MEDICATION.ENCOUNTER_MEDICATION;

    /**
     * The table <code>school.encounter_note</code>.
     */
    public final ENCOUNTER_NOTE ENCOUNTER_NOTE = zw.co.elearning.school.db.tables.ENCOUNTER_NOTE.ENCOUNTER_NOTE;

    /**
     * The table <code>school.encounter_procedure</code>.
     */
    public final ENCOUNTER_PROCEDURE ENCOUNTER_PROCEDURE = zw.co.elearning.school.db.tables.ENCOUNTER_PROCEDURE.ENCOUNTER_PROCEDURE;

    /**
     * The table <code>school.encounter_vital</code>.
     */
    public final ENCOUNTER_VITAL ENCOUNTER_VITAL = zw.co.elearning.school.db.tables.ENCOUNTER_VITAL.ENCOUNTER_VITAL;

    /**
     * The table <code>school.examination</code>.
     */
    public final EXAMINATION EXAMINATION = zw.co.elearning.school.db.tables.EXAMINATION.EXAMINATION;

    /**
     * The table <code>school.facility</code>.
     */
    public final FACILITY FACILITY = zw.co.elearning.school.db.tables.FACILITY.FACILITY;

    /**
     * The table <code>school.family_planning_method</code>.
     */
    public final FAMILY_PLANNING_METHOD FAMILY_PLANNING_METHOD = zw.co.elearning.school.db.tables.FAMILY_PLANNING_METHOD.FAMILY_PLANNING_METHOD;

    /**
     * The table <code>school.feeding_option</code>.
     */
    public final FEEDING_OPTION FEEDING_OPTION = zw.co.elearning.school.db.tables.FEEDING_OPTION.FEEDING_OPTION;

    /**
     * The table <code>school.foetal_death</code>.
     */
    public final FOETAL_DEATH FOETAL_DEATH = zw.co.elearning.school.db.tables.FOETAL_DEATH.FOETAL_DEATH;

    /**
     * The table <code>school.follow_up_status</code>.
     */
    public final FOLLOW_UP_STATUS FOLLOW_UP_STATUS = zw.co.elearning.school.db.tables.FOLLOW_UP_STATUS.FOLLOW_UP_STATUS;

    /**
     * The table <code>school.formulation</code>.
     */
    public final FORMULATION FORMULATION = zw.co.elearning.school.db.tables.FORMULATION.FORMULATION;

    /**
     * The table <code>school.frequency</code>.
     */
    public final FREQUENCY FREQUENCY = zw.co.elearning.school.db.tables.FREQUENCY.FREQUENCY;

    /**
     * The table <code>school.functional_status</code>.
     */
    public final FUNCTIONAL_STATUS FUNCTIONAL_STATUS = zw.co.elearning.school.db.tables.FUNCTIONAL_STATUS.FUNCTIONAL_STATUS;

    /**
     * The table <code>school.general_assessment</code>.
     */
    public final GENERAL_ASSESSMENT GENERAL_ASSESSMENT = zw.co.elearning.school.db.tables.GENERAL_ASSESSMENT.GENERAL_ASSESSMENT;

    /**
     * The table <code>school.health_education_topic</code>.
     */
    public final HEALTH_EDUCATION_TOPIC HEALTH_EDUCATION_TOPIC = zw.co.elearning.school.db.tables.HEALTH_EDUCATION_TOPIC.HEALTH_EDUCATION_TOPIC;

    /**
     * The table <code>school.hibernate_sequence</code>.
     */
    public final HIBERNATE_SEQUENCE HIBERNATE_SEQUENCE = zw.co.elearning.school.db.tables.HIBERNATE_SEQUENCE.HIBERNATE_SEQUENCE;

    /**
     * The table <code>school.hts</code>.
     */
    public final HTS HTS = zw.co.elearning.school.db.tables.HTS.HTS;

    /**
     * The table <code>school.hts_model</code>.
     */
    public final HTS_MODEL HTS_MODEL = zw.co.elearning.school.db.tables.HTS_MODEL.HTS_MODEL;

    /**
     * The table <code>school.hts_post_test_service</code>.
     */
    public final HTS_POST_TEST_SERVICE HTS_POST_TEST_SERVICE = zw.co.elearning.school.db.tables.HTS_POST_TEST_SERVICE.HTS_POST_TEST_SERVICE;

    /**
     * The table <code>school.hts_post_test_service_offered</code>.
     */
    public final HTS_POST_TEST_SERVICE_OFFERED HTS_POST_TEST_SERVICE_OFFERED = zw.co.elearning.school.db.tables.HTS_POST_TEST_SERVICE_OFFERED.HTS_POST_TEST_SERVICE_OFFERED;

    /**
     * The table <code>school.immunization_schedule</code>.
     */
    public final IMMUNIZATION_SCHEDULE IMMUNIZATION_SCHEDULE = zw.co.elearning.school.db.tables.IMMUNIZATION_SCHEDULE.IMMUNIZATION_SCHEDULE;

    /**
     * The table <code>school.imnci_category</code>.
     */
    public final IMNCI_CATEGORY IMNCI_CATEGORY = zw.co.elearning.school.db.tables.IMNCI_CATEGORY.IMNCI_CATEGORY;

    /**
     * The table <code>school.imnci_classification</code>.
     */
    public final IMNCI_CLASSIFICATION IMNCI_CLASSIFICATION = zw.co.elearning.school.db.tables.IMNCI_CLASSIFICATION.IMNCI_CLASSIFICATION;

    /**
     * The table <code>school.imnci_questionnaire</code>.
     */
    public final IMNCI_QUESTIONNAIRE IMNCI_QUESTIONNAIRE = zw.co.elearning.school.db.tables.IMNCI_QUESTIONNAIRE.IMNCI_QUESTIONNAIRE;

    /**
     * The table <code>school.imnci_visit</code>.
     */
    public final IMNCI_VISIT IMNCI_VISIT = zw.co.elearning.school.db.tables.IMNCI_VISIT.IMNCI_VISIT;

    /**
     * The table <code>school.imnci_visit_question</code>.
     */
    public final IMNCI_VISIT_QUESTION IMNCI_VISIT_QUESTION = zw.co.elearning.school.db.tables.IMNCI_VISIT_QUESTION.IMNCI_VISIT_QUESTION;

    /**
     * The table <code>school.infant</code>.
     */
    public final INFANT INFANT = zw.co.elearning.school.db.tables.INFANT.INFANT;

    /**
     * The table <code>school.investigation</code>.
     */
    public final INVESTIGATION INVESTIGATION = zw.co.elearning.school.db.tables.INVESTIGATION.INVESTIGATION;

    /**
     * The table <code>school.investigation_history</code>.
     */
    public final INVESTIGATION_HISTORY INVESTIGATION_HISTORY = zw.co.elearning.school.db.tables.INVESTIGATION_HISTORY.INVESTIGATION_HISTORY;

    /**
     * The table <code>school.investigation_result</code>.
     */
    public final INVESTIGATION_RESULT INVESTIGATION_RESULT = zw.co.elearning.school.db.tables.INVESTIGATION_RESULT.INVESTIGATION_RESULT;

    /**
     * The table <code>school.investigation_result_diagnoses</code>.
     */
    public final INVESTIGATION_RESULT_DIAGNOSES INVESTIGATION_RESULT_DIAGNOSES = zw.co.elearning.school.db.tables.INVESTIGATION_RESULT_DIAGNOSES.INVESTIGATION_RESULT_DIAGNOSES;

    /**
     * The table <code>school.investigation_test_kit</code>.
     */
    public final INVESTIGATION_TEST_KIT INVESTIGATION_TEST_KIT = zw.co.elearning.school.db.tables.INVESTIGATION_TEST_KIT.INVESTIGATION_TEST_KIT;

    /**
     * The table <code>school.ipt_reason</code>.
     */
    public final IPT_REASON IPT_REASON = zw.co.elearning.school.db.tables.IPT_REASON.IPT_REASON;

    /**
     * The table <code>school.ipt_status</code>.
     */
    public final IPT_STATUS IPT_STATUS = zw.co.elearning.school.db.tables.IPT_STATUS.IPT_STATUS;

    /**
     * The table <code>school.jhi_authority</code>.
     */
    public final JHI_AUTHORITY JHI_AUTHORITY = zw.co.elearning.school.db.tables.JHI_AUTHORITY.JHI_AUTHORITY;

    /**
     * The table <code>school.jhi_entity_audit_event</code>.
     */
    public final JHI_ENTITY_AUDIT_EVENT JHI_ENTITY_AUDIT_EVENT = zw.co.elearning.school.db.tables.JHI_ENTITY_AUDIT_EVENT.JHI_ENTITY_AUDIT_EVENT;

    /**
     * The table <code>school.jhi_persistent_audit_event</code>.
     */
    public final JHI_PERSISTENT_AUDIT_EVENT JHI_PERSISTENT_AUDIT_EVENT = zw.co.elearning.school.db.tables.JHI_PERSISTENT_AUDIT_EVENT.JHI_PERSISTENT_AUDIT_EVENT;

    /**
     * The table <code>school.jhi_persistent_audit_evt_data</code>.
     */
    public final JHI_PERSISTENT_AUDIT_EVT_DATA JHI_PERSISTENT_AUDIT_EVT_DATA = zw.co.elearning.school.db.tables.JHI_PERSISTENT_AUDIT_EVT_DATA.JHI_PERSISTENT_AUDIT_EVT_DATA;

    /**
     * The table <code>school.jhi_user</code>.
     */
    public final JHI_USER JHI_USER = zw.co.elearning.school.db.tables.JHI_USER.JHI_USER;

    /**
     * The table <code>school.jhi_user_authority</code>.
     */
    public final JHI_USER_AUTHORITY JHI_USER_AUTHORITY = zw.co.elearning.school.db.tables.JHI_USER_AUTHORITY.JHI_USER_AUTHORITY;

    /**
     * The table <code>school.laboratory</code>.
     */
    public final LABORATORY LABORATORY = zw.co.elearning.school.db.tables.LABORATORY.LABORATORY;

    /**
     * The table <code>school.labour_summary</code>.
     */
    public final LABOUR_SUMMARY LABOUR_SUMMARY = zw.co.elearning.school.db.tables.LABOUR_SUMMARY.LABOUR_SUMMARY;

    /**
     * The table <code>school.lab_result</code>.
     */
    public final LAB_RESULT LAB_RESULT = zw.co.elearning.school.db.tables.LAB_RESULT.LAB_RESULT;

    /**
     * The table <code>school.lab_test</code>.
     */
    public final LAB_TEST LAB_TEST = zw.co.elearning.school.db.tables.LAB_TEST.LAB_TEST;

    /**
     * The table <code>school.level_of_presenting_part</code>.
     */
    public final LEVEL_OF_PRESENTING_PART LEVEL_OF_PRESENTING_PART = zw.co.elearning.school.db.tables.LEVEL_OF_PRESENTING_PART.LEVEL_OF_PRESENTING_PART;

    /**
     * The table <code>school.marital_state</code>.
     */
    public final MARITAL_STATE MARITAL_STATE = zw.co.elearning.school.db.tables.MARITAL_STATE.MARITAL_STATE;

    /**
     * The table <code>school.maternal_death</code>.
     */
    public final MATERNAL_DEATH MATERNAL_DEATH = zw.co.elearning.school.db.tables.MATERNAL_DEATH.MATERNAL_DEATH;

    /**
     * The table <code>school.maternal_death_factor</code>.
     */
    public final MATERNAL_DEATH_FACTOR MATERNAL_DEATH_FACTOR = zw.co.elearning.school.db.tables.MATERNAL_DEATH_FACTOR.MATERNAL_DEATH_FACTOR;

    /**
     * The table <code>school.medical_aid</code>.
     */
    public final MEDICAL_AID MEDICAL_AID = zw.co.elearning.school.db.tables.MEDICAL_AID.MEDICAL_AID;

    /**
     * The table <code>school.medical_aid_provider</code>.
     */
    public final MEDICAL_AID_PROVIDER MEDICAL_AID_PROVIDER = zw.co.elearning.school.db.tables.MEDICAL_AID_PROVIDER.MEDICAL_AID_PROVIDER;

    /**
     * The table <code>school.medical_procedure</code>.
     */
    public final MEDICAL_PROCEDURE MEDICAL_PROCEDURE = zw.co.elearning.school.db.tables.MEDICAL_PROCEDURE.MEDICAL_PROCEDURE;

    /**
     * The table <code>school.nurse_general_examination</code>.
     */
    public final NURSE_GENERAL_EXAMINATION NURSE_GENERAL_EXAMINATION = zw.co.elearning.school.db.tables.NURSE_GENERAL_EXAMINATION.NURSE_GENERAL_EXAMINATION;

    /**
     * The table <code>school.nurse_vaginal_examination</code>.
     */
    public final NURSE_VAGINAL_EXAMINATION NURSE_VAGINAL_EXAMINATION = zw.co.elearning.school.db.tables.NURSE_VAGINAL_EXAMINATION.NURSE_VAGINAL_EXAMINATION;

    /**
     * The table <code>school.obstetric_examination</code>.
     */
    public final OBSTETRIC_EXAMINATION OBSTETRIC_EXAMINATION = zw.co.elearning.school.db.tables.OBSTETRIC_EXAMINATION.OBSTETRIC_EXAMINATION;

    /**
     * The table <code>school.obstretric_examination</code>.
     */
    public final OBSTRETRIC_EXAMINATION OBSTRETRIC_EXAMINATION = zw.co.elearning.school.db.tables.OBSTRETRIC_EXAMINATION.OBSTRETRIC_EXAMINATION;

    /**
     * The table <code>school.occupation</code>.
     */
    public final OCCUPATION OCCUPATION = zw.co.elearning.school.db.tables.OCCUPATION.OCCUPATION;

    /**
     * The table <code>school.opd</code>.
     */
    public final OPD OPD = zw.co.elearning.school.db.tables.OPD.OPD;

    /**
     * The table <code>school.opd_encounter</code>.
     */
    public final OPD_ENCOUNTER OPD_ENCOUNTER = zw.co.elearning.school.db.tables.OPD_ENCOUNTER.OPD_ENCOUNTER;

    /**
     * The table <code>school.opd_queue</code>.
     */
    public final OPD_QUEUE OPD_QUEUE = zw.co.elearning.school.db.tables.OPD_QUEUE.OPD_QUEUE;

    /**
     * The table <code>school.perinium_repair_type</code>.
     */
    public final PERINIUM_REPAIR_TYPE PERINIUM_REPAIR_TYPE = zw.co.elearning.school.db.tables.PERINIUM_REPAIR_TYPE.PERINIUM_REPAIR_TYPE;

    /**
     * The table <code>school.person</code>.
     */
    public final PERSON PERSON = zw.co.elearning.school.db.tables.PERSON.PERSON;

    /**
     * The table <code>school.person_allergy</code>.
     */
    public final PERSON_ALLERGY PERSON_ALLERGY = zw.co.elearning.school.db.tables.PERSON_ALLERGY.PERSON_ALLERGY;

    /**
     * The table <code>school.person_art_follow_up_status</code>.
     */
    public final PERSON_ART_FOLLOW_UP_STATUS PERSON_ART_FOLLOW_UP_STATUS = zw.co.elearning.school.db.tables.PERSON_ART_FOLLOW_UP_STATUS.PERSON_ART_FOLLOW_UP_STATUS;

    /**
     * The table <code>school.person_art_functional_status</code>.
     */
    public final PERSON_ART_FUNCTIONAL_STATUS PERSON_ART_FUNCTIONAL_STATUS = zw.co.elearning.school.db.tables.PERSON_ART_FUNCTIONAL_STATUS.PERSON_ART_FUNCTIONAL_STATUS;

    /**
     * The table <code>school.person_art_ipt_status</code>.
     */
    public final PERSON_ART_IPT_STATUS PERSON_ART_IPT_STATUS = zw.co.elearning.school.db.tables.PERSON_ART_IPT_STATUS.PERSON_ART_IPT_STATUS;

    /**
     * The table <code>school.person_art_regimen</code>.
     */
    public final PERSON_ART_REGIMEN PERSON_ART_REGIMEN = zw.co.elearning.school.db.tables.PERSON_ART_REGIMEN.PERSON_ART_REGIMEN;

    /**
     * The table <code>school.person_art_status</code>.
     */
    public final PERSON_ART_STATUS PERSON_ART_STATUS = zw.co.elearning.school.db.tables.PERSON_ART_STATUS.PERSON_ART_STATUS;

    /**
     * The table <code>school.person_art_who_stage</code>.
     */
    public final PERSON_ART_WHO_STAGE PERSON_ART_WHO_STAGE = zw.co.elearning.school.db.tables.PERSON_ART_WHO_STAGE.PERSON_ART_WHO_STAGE;

    /**
     * The table <code>school.person_complaint</code>.
     */
    public final PERSON_COMPLAINT PERSON_COMPLAINT = zw.co.elearning.school.db.tables.PERSON_COMPLAINT.PERSON_COMPLAINT;

    /**
     * The table <code>school.person_diagnosis</code>.
     */
    public final PERSON_DIAGNOSIS PERSON_DIAGNOSIS = zw.co.elearning.school.db.tables.PERSON_DIAGNOSIS.PERSON_DIAGNOSIS;

    /**
     * The table <code>school.person_examination</code>.
     */
    public final PERSON_EXAMINATION PERSON_EXAMINATION = zw.co.elearning.school.db.tables.PERSON_EXAMINATION.PERSON_EXAMINATION;

    /**
     * The table <code>school.person_health_education</code>.
     */
    public final PERSON_HEALTH_EDUCATION PERSON_HEALTH_EDUCATION = zw.co.elearning.school.db.tables.PERSON_HEALTH_EDUCATION.PERSON_HEALTH_EDUCATION;

    /**
     * The table <code>school.person_id</code>.
     */
    public final PERSON_ID PERSON_ID = zw.co.elearning.school.db.tables.PERSON_ID.PERSON_ID;

    /**
     * The table <code>school.person_identifier</code>.
     */
    public final PERSON_IDENTIFIER PERSON_IDENTIFIER = zw.co.elearning.school.db.tables.PERSON_IDENTIFIER.PERSON_IDENTIFIER;

    /**
     * The table <code>school.person_investigation</code>.
     */
    public final PERSON_INVESTIGATION PERSON_INVESTIGATION = zw.co.elearning.school.db.tables.PERSON_INVESTIGATION.PERSON_INVESTIGATION;

    /**
     * The table <code>school.person_investigation_test</code>.
     */
    public final PERSON_INVESTIGATION_TEST PERSON_INVESTIGATION_TEST = zw.co.elearning.school.db.tables.PERSON_INVESTIGATION_TEST.PERSON_INVESTIGATION_TEST;

    /**
     * The table <code>school.person_medication</code>.
     */
    public final PERSON_MEDICATION PERSON_MEDICATION = zw.co.elearning.school.db.tables.PERSON_MEDICATION.PERSON_MEDICATION;

    /**
     * The table <code>school.person_procedure</code>.
     */
    public final PERSON_PROCEDURE PERSON_PROCEDURE = zw.co.elearning.school.db.tables.PERSON_PROCEDURE.PERSON_PROCEDURE;

    /**
     * The table <code>school.person_vital</code>.
     */
    public final PERSON_VITAL PERSON_VITAL = zw.co.elearning.school.db.tables.PERSON_VITAL.PERSON_VITAL;

    /**
     * The table <code>school.phone</code>.
     */
    public final PHONE PHONE = zw.co.elearning.school.db.tables.PHONE.PHONE;

    /**
     * The table <code>school.placenta_and_membrane</code>.
     */
    public final PLACENTA_AND_MEMBRANE PLACENTA_AND_MEMBRANE = zw.co.elearning.school.db.tables.PLACENTA_AND_MEMBRANE.PLACENTA_AND_MEMBRANE;

    /**
     * The table <code>school.placenta_delivery_type</code>.
     */
    public final PLACENTA_DELIVERY_TYPE PLACENTA_DELIVERY_TYPE = zw.co.elearning.school.db.tables.PLACENTA_DELIVERY_TYPE.PLACENTA_DELIVERY_TYPE;

    /**
     * The table <code>school.pnc</code>.
     */
    public final PNC PNC = zw.co.elearning.school.db.tables.PNC.PNC;

    /**
     * The table <code>school.pnc_child</code>.
     */
    public final PNC_CHILD PNC_CHILD = zw.co.elearning.school.db.tables.PNC_CHILD.PNC_CHILD;

    /**
     * The table <code>school.pnc_property</code>.
     */
    public final PNC_PROPERTY PNC_PROPERTY = zw.co.elearning.school.db.tables.PNC_PROPERTY.PNC_PROPERTY;

    /**
     * The table <code>school.pnc_questionare</code>.
     */
    public final PNC_QUESTIONARE PNC_QUESTIONARE = zw.co.elearning.school.db.tables.PNC_QUESTIONARE.PNC_QUESTIONARE;

    /**
     * The table <code>school.pnc_questionare_category</code>.
     */
    public final PNC_QUESTIONARE_CATEGORY PNC_QUESTIONARE_CATEGORY = zw.co.elearning.school.db.tables.PNC_QUESTIONARE_CATEGORY.PNC_QUESTIONARE_CATEGORY;

    /**
     * The table <code>school.pnc_visit</code>.
     */
    public final PNC_VISIT PNC_VISIT = zw.co.elearning.school.db.tables.PNC_VISIT.PNC_VISIT;

    /**
     * The table <code>school.pnc_visit_type</code>.
     */
    public final PNC_VISIT_TYPE PNC_VISIT_TYPE = zw.co.elearning.school.db.tables.PNC_VISIT_TYPE.PNC_VISIT_TYPE;

    /**
     * The table <code>school.prescription</code>.
     */
    public final PRESCRIPTION PRESCRIPTION = zw.co.elearning.school.db.tables.PRESCRIPTION.PRESCRIPTION;

    /**
     * The table <code>school.province</code>.
     */
    public final PROVINCE PROVINCE = zw.co.elearning.school.db.tables.PROVINCE.PROVINCE;

    /**
     * The table <code>school.purpose_of_test</code>.
     */
    public final PURPOSE_OF_TEST PURPOSE_OF_TEST = zw.co.elearning.school.db.tables.PURPOSE_OF_TEST.PURPOSE_OF_TEST;

    /**
     * The table <code>school.queue</code>.
     */
    public final QUEUE QUEUE = zw.co.elearning.school.db.tables.QUEUE.QUEUE;

    /**
     * The table <code>school.reason_for_not_issuing_result</code>.
     */
    public final REASON_FOR_NOT_ISSUING_RESULT REASON_FOR_NOT_ISSUING_RESULT = zw.co.elearning.school.db.tables.REASON_FOR_NOT_ISSUING_RESULT.REASON_FOR_NOT_ISSUING_RESULT;

    /**
     * The table <code>school.referral</code>.
     */
    public final REFERRAL REFERRAL = zw.co.elearning.school.db.tables.REFERRAL.REFERRAL;

    /**
     * The table <code>school.referral_reason</code>.
     */
    public final REFERRAL_REASON REFERRAL_REASON = zw.co.elearning.school.db.tables.REFERRAL_REASON.REFERRAL_REASON;

    /**
     * The table <code>school.relation</code>.
     */
    public final RELATION RELATION = zw.co.elearning.school.db.tables.RELATION.RELATION;

    /**
     * The table <code>school.relationship_type</code>.
     */
    public final RELATIONSHIP_TYPE RELATIONSHIP_TYPE = zw.co.elearning.school.db.tables.RELATIONSHIP_TYPE.RELATIONSHIP_TYPE;

    /**
     * The table <code>school.sample</code>.
     */
    public final SAMPLE SAMPLE = zw.co.elearning.school.db.tables.SAMPLE.SAMPLE;

    /**
     * The table <code>school.site_setting</code>.
     */
    public final SITE_SETTING SITE_SETTING = zw.co.elearning.school.db.tables.SITE_SETTING.SITE_SETTING;

    /**
     * The table <code>school.stage</code>.
     */
    public final STAGE STAGE = zw.co.elearning.school.db.tables.STAGE.STAGE;

    /**
     * The table <code>school.stage_number</code>.
     */
    public final STAGE_NUMBER STAGE_NUMBER = zw.co.elearning.school.db.tables.STAGE_NUMBER.STAGE_NUMBER;

    /**
     * The table <code>school.standard</code>.
     */
    public final STANDARD STANDARD = zw.co.elearning.school.db.tables.STANDARD.STANDARD;

    /**
     * The table <code>school.supplier</code>.
     */
    public final SUPPLIER SUPPLIER = zw.co.elearning.school.db.tables.SUPPLIER.SUPPLIER;

    /**
     * The table <code>school.tb</code>.
     */
    public final TB TB = zw.co.elearning.school.db.tables.TB.TB;

    /**
     * The table <code>school.tb_category</code>.
     */
    public final TB_CATEGORY TB_CATEGORY = zw.co.elearning.school.db.tables.TB_CATEGORY.TB_CATEGORY;

    /**
     * The table <code>school.tb_questionare</code>.
     */
    public final TB_QUESTIONARE TB_QUESTIONARE = zw.co.elearning.school.db.tables.TB_QUESTIONARE.TB_QUESTIONARE;

    /**
     * The table <code>school.tb_risk_group</code>.
     */
    public final TB_RISK_GROUP TB_RISK_GROUP = zw.co.elearning.school.db.tables.TB_RISK_GROUP.TB_RISK_GROUP;

    /**
     * The table <code>school.tb_status</code>.
     */
    public final TB_STATUS TB_STATUS = zw.co.elearning.school.db.tables.TB_STATUS.TB_STATUS;

    /**
     * The table <code>school.tb_survey</code>.
     */
    public final TB_SURVEY TB_SURVEY = zw.co.elearning.school.db.tables.TB_SURVEY.TB_SURVEY;

    /**
     * The table <code>school.tb_visit</code>.
     */
    public final TB_VISIT TB_VISIT = zw.co.elearning.school.db.tables.TB_VISIT.TB_VISIT;

    /**
     * The table <code>school.test_kit</code>.
     */
    public final TEST_KIT TEST_KIT = zw.co.elearning.school.db.tables.TEST_KIT.TEST_KIT;

    /**
     * The table <code>school.test_kit_batch</code>.
     */
    public final TEST_KIT_BATCH TEST_KIT_BATCH = zw.co.elearning.school.db.tables.TEST_KIT_BATCH.TEST_KIT_BATCH;

    /**
     * The table <code>school.town</code>.
     */
    public final TOWN TOWN = zw.co.elearning.school.db.tables.TOWN.TOWN;

    /**
     * The table <code>school.unit</code>.
     */
    public final UNIT UNIT = zw.co.elearning.school.db.tables.UNIT.UNIT;

    /**
     * The table <code>school.vaginal_monitoring</code>.
     */
    public final VAGINAL_MONITORING VAGINAL_MONITORING = zw.co.elearning.school.db.tables.VAGINAL_MONITORING.VAGINAL_MONITORING;

    /**
     * The table <code>school.vital</code>.
     */
    public final VITAL VITAL = zw.co.elearning.school.db.tables.VITAL.VITAL;

    /**
     * The table <code>school.ward</code>.
     */
    public final WARD WARD = zw.co.elearning.school.db.tables.WARD.WARD;

    /**
     * The table <code>school.zepi_drug_name</code>.
     */
    public final ZEPI_DRUG_NAME ZEPI_DRUG_NAME = zw.co.elearning.school.db.tables.ZEPI_DRUG_NAME.ZEPI_DRUG_NAME;

    /**
     * No further instances allowed
     */
    private School() {
        super("school", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ADDRESS.ADDRESS,
            ADMISSION.ADMISSION,
            ADMISSION_ENCOUNTER.ADMISSION_ENCOUNTER,
            ALLERGY.ALLERGY,
            AMNIOTIC_FLUID.AMNIOTIC_FLUID,
            ANC.ANC,
            ANC_HISTORY.ANC_HISTORY,
            ANC_QUESTIONARE.ANC_QUESTIONARE,
            ANC_VISIT.ANC_VISIT,
            APPOINTMENT.APPOINTMENT,
            APPOINTMENT_CANCELLATION_REASON.APPOINTMENT_CANCELLATION_REASON,
            APPOINTMENT_REASON.APPOINTMENT_REASON,
            APPOINTMENT_RESCHEDULLING_REASON.APPOINTMENT_RESCHEDULLING_REASON,
            ART.ART,
            ART_CURRENT_SIGN.ART_CURRENT_SIGN,
            ART_CURRENT_SYMPTOM.ART_CURRENT_SYMPTOM,
            ART_INVESTIGATION_HISTORY.ART_INVESTIGATION_HISTORY,
            ART_MEDICAL_HISTORY.ART_MEDICAL_HISTORY,
            ART_MEDICATION_HISTORY.ART_MEDICATION_HISTORY,
            ART_QUESTIONARE.ART_QUESTIONARE,
            ART_REASON.ART_REASON,
            ART_STATUS.ART_STATUS,
            ART_VISIT.ART_VISIT,
            ART_VISIT_NEW_OI.ART_VISIT_NEW_OI,
            ART_VISIT_STATUS.ART_VISIT_STATUS,
            ART_VISIT_TYPE.ART_VISIT_TYPE,
            ARV_COMBINATION_REGIMEN.ARV_COMBINATION_REGIMEN,
            CERVIX.CERVIX,
            COMPLAINT.COMPLAINT,
            CONTRACTION.CONTRACTION,
            DEGREE.DEGREE,
            DEGREE_OF_MOULDING.DEGREE_OF_MOULDING,
            DELIVERY.DELIVERY,
            DELIVERY_HISTORY.DELIVERY_HISTORY,
            DELIVERY_MATERNAL_DEATH_FACTOR.DELIVERY_MATERNAL_DEATH_FACTOR,
            DELIVERY_PARTOGRAM.DELIVERY_PARTOGRAM,
            DELIVERY_QUESTIONARE.DELIVERY_QUESTIONARE,
            DELIVERY_SUMMARY.DELIVERY_SUMMARY,
            DELIVERY_TYPE.DELIVERY_TYPE,
            DEPARTMENT.DEPARTMENT,
            DIAGNOSIS.DIAGNOSIS,
            DISPENSE.DISPENSE,
            DISTRICT.DISTRICT,
            DOCTOR_GENERAL_EXAMINATION.DOCTOR_GENERAL_EXAMINATION,
            DOCTOR_VAGINAL_EXAMINATION.DOCTOR_VAGINAL_EXAMINATION,
            DRUG.DRUG,
            DRUG_BATCH.DRUG_BATCH,
            DRUG_NAME.DRUG_NAME,
            DRUG_OPTION.DRUG_OPTION,
            DRUG_SUFFIX.DRUG_SUFFIX,
            EDUCATION_LEVEL.EDUCATION_LEVEL,
            EMAIL.EMAIL,
            ENCOUNTER.ENCOUNTER,
            ENCOUNTER_COMPLAINT.ENCOUNTER_COMPLAINT,
            ENCOUNTER_DIAGNOSIS.ENCOUNTER_DIAGNOSIS,
            ENCOUNTER_EXAMINATION.ENCOUNTER_EXAMINATION,
            ENCOUNTER_HEALTH_EDUCATION.ENCOUNTER_HEALTH_EDUCATION,
            ENCOUNTER_INVESTIGATION.ENCOUNTER_INVESTIGATION,
            ENCOUNTER_MEDICATION.ENCOUNTER_MEDICATION,
            ENCOUNTER_NOTE.ENCOUNTER_NOTE,
            ENCOUNTER_PROCEDURE.ENCOUNTER_PROCEDURE,
            ENCOUNTER_VITAL.ENCOUNTER_VITAL,
            EXAMINATION.EXAMINATION,
            FACILITY.FACILITY,
            FAMILY_PLANNING_METHOD.FAMILY_PLANNING_METHOD,
            FEEDING_OPTION.FEEDING_OPTION,
            FOETAL_DEATH.FOETAL_DEATH,
            FOLLOW_UP_STATUS.FOLLOW_UP_STATUS,
            FORMULATION.FORMULATION,
            FREQUENCY.FREQUENCY,
            FUNCTIONAL_STATUS.FUNCTIONAL_STATUS,
            GENERAL_ASSESSMENT.GENERAL_ASSESSMENT,
            HEALTH_EDUCATION_TOPIC.HEALTH_EDUCATION_TOPIC,
            HIBERNATE_SEQUENCE.HIBERNATE_SEQUENCE,
            HTS.HTS,
            HTS_MODEL.HTS_MODEL,
            HTS_POST_TEST_SERVICE.HTS_POST_TEST_SERVICE,
            HTS_POST_TEST_SERVICE_OFFERED.HTS_POST_TEST_SERVICE_OFFERED,
            IMMUNIZATION_SCHEDULE.IMMUNIZATION_SCHEDULE,
            IMNCI_CATEGORY.IMNCI_CATEGORY,
            IMNCI_CLASSIFICATION.IMNCI_CLASSIFICATION,
            IMNCI_QUESTIONNAIRE.IMNCI_QUESTIONNAIRE,
            IMNCI_VISIT.IMNCI_VISIT,
            IMNCI_VISIT_QUESTION.IMNCI_VISIT_QUESTION,
            INFANT.INFANT,
            INVESTIGATION.INVESTIGATION,
            INVESTIGATION_HISTORY.INVESTIGATION_HISTORY,
            INVESTIGATION_RESULT.INVESTIGATION_RESULT,
            INVESTIGATION_RESULT_DIAGNOSES.INVESTIGATION_RESULT_DIAGNOSES,
            INVESTIGATION_TEST_KIT.INVESTIGATION_TEST_KIT,
            IPT_REASON.IPT_REASON,
            IPT_STATUS.IPT_STATUS,
            JHI_AUTHORITY.JHI_AUTHORITY,
            JHI_ENTITY_AUDIT_EVENT.JHI_ENTITY_AUDIT_EVENT,
            JHI_PERSISTENT_AUDIT_EVENT.JHI_PERSISTENT_AUDIT_EVENT,
            JHI_PERSISTENT_AUDIT_EVT_DATA.JHI_PERSISTENT_AUDIT_EVT_DATA,
            JHI_USER.JHI_USER,
            JHI_USER_AUTHORITY.JHI_USER_AUTHORITY,
            LABORATORY.LABORATORY,
            LABOUR_SUMMARY.LABOUR_SUMMARY,
            LAB_RESULT.LAB_RESULT,
            LAB_TEST.LAB_TEST,
            LEVEL_OF_PRESENTING_PART.LEVEL_OF_PRESENTING_PART,
            MARITAL_STATE.MARITAL_STATE,
            MATERNAL_DEATH.MATERNAL_DEATH,
            MATERNAL_DEATH_FACTOR.MATERNAL_DEATH_FACTOR,
            MEDICAL_AID.MEDICAL_AID,
            MEDICAL_AID_PROVIDER.MEDICAL_AID_PROVIDER,
            MEDICAL_PROCEDURE.MEDICAL_PROCEDURE,
            NURSE_GENERAL_EXAMINATION.NURSE_GENERAL_EXAMINATION,
            NURSE_VAGINAL_EXAMINATION.NURSE_VAGINAL_EXAMINATION,
            OBSTETRIC_EXAMINATION.OBSTETRIC_EXAMINATION,
            OBSTRETRIC_EXAMINATION.OBSTRETRIC_EXAMINATION,
            OCCUPATION.OCCUPATION,
            OPD.OPD,
            OPD_ENCOUNTER.OPD_ENCOUNTER,
            OPD_QUEUE.OPD_QUEUE,
            PERINIUM_REPAIR_TYPE.PERINIUM_REPAIR_TYPE,
            PERSON.PERSON,
            PERSON_ALLERGY.PERSON_ALLERGY,
            PERSON_ART_FOLLOW_UP_STATUS.PERSON_ART_FOLLOW_UP_STATUS,
            PERSON_ART_FUNCTIONAL_STATUS.PERSON_ART_FUNCTIONAL_STATUS,
            PERSON_ART_IPT_STATUS.PERSON_ART_IPT_STATUS,
            PERSON_ART_REGIMEN.PERSON_ART_REGIMEN,
            PERSON_ART_STATUS.PERSON_ART_STATUS,
            PERSON_ART_WHO_STAGE.PERSON_ART_WHO_STAGE,
            PERSON_COMPLAINT.PERSON_COMPLAINT,
            PERSON_DIAGNOSIS.PERSON_DIAGNOSIS,
            PERSON_EXAMINATION.PERSON_EXAMINATION,
            PERSON_HEALTH_EDUCATION.PERSON_HEALTH_EDUCATION,
            PERSON_ID.PERSON_ID,
            PERSON_IDENTIFIER.PERSON_IDENTIFIER,
            PERSON_INVESTIGATION.PERSON_INVESTIGATION,
            PERSON_INVESTIGATION_TEST.PERSON_INVESTIGATION_TEST,
            PERSON_MEDICATION.PERSON_MEDICATION,
            PERSON_PROCEDURE.PERSON_PROCEDURE,
            PERSON_VITAL.PERSON_VITAL,
            PHONE.PHONE,
            PLACENTA_AND_MEMBRANE.PLACENTA_AND_MEMBRANE,
            PLACENTA_DELIVERY_TYPE.PLACENTA_DELIVERY_TYPE,
            PNC.PNC,
            PNC_CHILD.PNC_CHILD,
            PNC_PROPERTY.PNC_PROPERTY,
            PNC_QUESTIONARE.PNC_QUESTIONARE,
            PNC_QUESTIONARE_CATEGORY.PNC_QUESTIONARE_CATEGORY,
            PNC_VISIT.PNC_VISIT,
            PNC_VISIT_TYPE.PNC_VISIT_TYPE,
            PRESCRIPTION.PRESCRIPTION,
            PROVINCE.PROVINCE,
            PURPOSE_OF_TEST.PURPOSE_OF_TEST,
            QUEUE.QUEUE,
            REASON_FOR_NOT_ISSUING_RESULT.REASON_FOR_NOT_ISSUING_RESULT,
            REFERRAL.REFERRAL,
            REFERRAL_REASON.REFERRAL_REASON,
            RELATION.RELATION,
            RELATIONSHIP_TYPE.RELATIONSHIP_TYPE,
            SAMPLE.SAMPLE,
            SITE_SETTING.SITE_SETTING,
            STAGE.STAGE,
            STAGE_NUMBER.STAGE_NUMBER,
            STANDARD.STANDARD,
            SUPPLIER.SUPPLIER,
            TB.TB,
            TB_CATEGORY.TB_CATEGORY,
            TB_QUESTIONARE.TB_QUESTIONARE,
            TB_RISK_GROUP.TB_RISK_GROUP,
            TB_STATUS.TB_STATUS,
            TB_SURVEY.TB_SURVEY,
            TB_VISIT.TB_VISIT,
            TEST_KIT.TEST_KIT,
            TEST_KIT_BATCH.TEST_KIT_BATCH,
            TOWN.TOWN,
            UNIT.UNIT,
            VAGINAL_MONITORING.VAGINAL_MONITORING,
            VITAL.VITAL,
            WARD.WARD,
            ZEPI_DRUG_NAME.ZEPI_DRUG_NAME);
    }
}
