/*
 * This file is generated by jOOQ.
*/
package zw.co.elearning.school.db;


import javax.annotation.Generated;

import zw.co.elearning.school.db.tables.ADDRESS;
import zw.co.elearning.school.db.tables.ADMISSION;
import zw.co.elearning.school.db.tables.ADMISSION_ENCOUNTER;
import zw.co.elearning.school.db.tables.ALLERGY;
import zw.co.elearning.school.db.tables.AMNIOTIC_FLUID;
import zw.co.elearning.school.db.tables.ANC;
import zw.co.elearning.school.db.tables.ANC_HISTORY;
import zw.co.elearning.school.db.tables.ANC_QUESTIONARE;
import zw.co.elearning.school.db.tables.ANC_VISIT;
import zw.co.elearning.school.db.tables.APPOINTMENT;
import zw.co.elearning.school.db.tables.APPOINTMENT_CANCELLATION_REASON;
import zw.co.elearning.school.db.tables.APPOINTMENT_REASON;
import zw.co.elearning.school.db.tables.APPOINTMENT_RESCHEDULLING_REASON;
import zw.co.elearning.school.db.tables.ART;
import zw.co.elearning.school.db.tables.ART_CURRENT_SIGN;
import zw.co.elearning.school.db.tables.ART_CURRENT_SYMPTOM;
import zw.co.elearning.school.db.tables.ART_INVESTIGATION_HISTORY;
import zw.co.elearning.school.db.tables.ART_MEDICAL_HISTORY;
import zw.co.elearning.school.db.tables.ART_MEDICATION_HISTORY;
import zw.co.elearning.school.db.tables.ART_QUESTIONARE;
import zw.co.elearning.school.db.tables.ART_REASON;
import zw.co.elearning.school.db.tables.ART_STATUS;
import zw.co.elearning.school.db.tables.ART_VISIT;
import zw.co.elearning.school.db.tables.ART_VISIT_NEW_OI;
import zw.co.elearning.school.db.tables.ART_VISIT_STATUS;
import zw.co.elearning.school.db.tables.ART_VISIT_TYPE;
import zw.co.elearning.school.db.tables.ARV_COMBINATION_REGIMEN;
import zw.co.elearning.school.db.tables.CERVIX;
import zw.co.elearning.school.db.tables.COMPLAINT;
import zw.co.elearning.school.db.tables.CONTRACTION;
import zw.co.elearning.school.db.tables.DEGREE;
import zw.co.elearning.school.db.tables.DEGREE_OF_MOULDING;
import zw.co.elearning.school.db.tables.DELIVERY;
import zw.co.elearning.school.db.tables.DELIVERY_HISTORY;
import zw.co.elearning.school.db.tables.DELIVERY_MATERNAL_DEATH_FACTOR;
import zw.co.elearning.school.db.tables.DELIVERY_PARTOGRAM;
import zw.co.elearning.school.db.tables.DELIVERY_QUESTIONARE;
import zw.co.elearning.school.db.tables.DELIVERY_SUMMARY;
import zw.co.elearning.school.db.tables.DELIVERY_TYPE;
import zw.co.elearning.school.db.tables.DEPARTMENT;
import zw.co.elearning.school.db.tables.DIAGNOSIS;
import zw.co.elearning.school.db.tables.DISPENSE;
import zw.co.elearning.school.db.tables.DISTRICT;
import zw.co.elearning.school.db.tables.DOCTOR_GENERAL_EXAMINATION;
import zw.co.elearning.school.db.tables.DOCTOR_VAGINAL_EXAMINATION;
import zw.co.elearning.school.db.tables.DRUG;
import zw.co.elearning.school.db.tables.DRUG_BATCH;
import zw.co.elearning.school.db.tables.DRUG_NAME;
import zw.co.elearning.school.db.tables.DRUG_OPTION;
import zw.co.elearning.school.db.tables.DRUG_SUFFIX;
import zw.co.elearning.school.db.tables.EDUCATION_LEVEL;
import zw.co.elearning.school.db.tables.EMAIL;
import zw.co.elearning.school.db.tables.ENCOUNTER;
import zw.co.elearning.school.db.tables.ENCOUNTER_COMPLAINT;
import zw.co.elearning.school.db.tables.ENCOUNTER_DIAGNOSIS;
import zw.co.elearning.school.db.tables.ENCOUNTER_EXAMINATION;
import zw.co.elearning.school.db.tables.ENCOUNTER_HEALTH_EDUCATION;
import zw.co.elearning.school.db.tables.ENCOUNTER_INVESTIGATION;
import zw.co.elearning.school.db.tables.ENCOUNTER_MEDICATION;
import zw.co.elearning.school.db.tables.ENCOUNTER_NOTE;
import zw.co.elearning.school.db.tables.ENCOUNTER_PROCEDURE;
import zw.co.elearning.school.db.tables.ENCOUNTER_VITAL;
import zw.co.elearning.school.db.tables.EXAMINATION;
import zw.co.elearning.school.db.tables.FACILITY;
import zw.co.elearning.school.db.tables.FAMILY_PLANNING_METHOD;
import zw.co.elearning.school.db.tables.FEEDING_OPTION;
import zw.co.elearning.school.db.tables.FOETAL_DEATH;
import zw.co.elearning.school.db.tables.FOLLOW_UP_STATUS;
import zw.co.elearning.school.db.tables.FORMULATION;
import zw.co.elearning.school.db.tables.FREQUENCY;
import zw.co.elearning.school.db.tables.FUNCTIONAL_STATUS;
import zw.co.elearning.school.db.tables.GENERAL_ASSESSMENT;
import zw.co.elearning.school.db.tables.HEALTH_EDUCATION_TOPIC;
import zw.co.elearning.school.db.tables.HIBERNATE_SEQUENCE;
import zw.co.elearning.school.db.tables.HTS;
import zw.co.elearning.school.db.tables.HTS_MODEL;
import zw.co.elearning.school.db.tables.HTS_POST_TEST_SERVICE;
import zw.co.elearning.school.db.tables.HTS_POST_TEST_SERVICE_OFFERED;
import zw.co.elearning.school.db.tables.IMMUNIZATION_SCHEDULE;
import zw.co.elearning.school.db.tables.IMNCI_CATEGORY;
import zw.co.elearning.school.db.tables.IMNCI_CLASSIFICATION;
import zw.co.elearning.school.db.tables.IMNCI_QUESTIONNAIRE;
import zw.co.elearning.school.db.tables.IMNCI_VISIT;
import zw.co.elearning.school.db.tables.IMNCI_VISIT_QUESTION;
import zw.co.elearning.school.db.tables.INFANT;
import zw.co.elearning.school.db.tables.INVESTIGATION;
import zw.co.elearning.school.db.tables.INVESTIGATION_HISTORY;
import zw.co.elearning.school.db.tables.INVESTIGATION_RESULT;
import zw.co.elearning.school.db.tables.INVESTIGATION_RESULT_DIAGNOSES;
import zw.co.elearning.school.db.tables.INVESTIGATION_TEST_KIT;
import zw.co.elearning.school.db.tables.IPT_REASON;
import zw.co.elearning.school.db.tables.IPT_STATUS;
import zw.co.elearning.school.db.tables.JHI_AUTHORITY;
import zw.co.elearning.school.db.tables.JHI_ENTITY_AUDIT_EVENT;
import zw.co.elearning.school.db.tables.JHI_PERSISTENT_AUDIT_EVENT;
import zw.co.elearning.school.db.tables.JHI_PERSISTENT_AUDIT_EVT_DATA;
import zw.co.elearning.school.db.tables.JHI_USER;
import zw.co.elearning.school.db.tables.JHI_USER_AUTHORITY;
import zw.co.elearning.school.db.tables.LABORATORY;
import zw.co.elearning.school.db.tables.LABOUR_SUMMARY;
import zw.co.elearning.school.db.tables.LAB_RESULT;
import zw.co.elearning.school.db.tables.LAB_TEST;
import zw.co.elearning.school.db.tables.LEVEL_OF_PRESENTING_PART;
import zw.co.elearning.school.db.tables.MARITAL_STATE;
import zw.co.elearning.school.db.tables.MATERNAL_DEATH;
import zw.co.elearning.school.db.tables.MATERNAL_DEATH_FACTOR;
import zw.co.elearning.school.db.tables.MEDICAL_AID;
import zw.co.elearning.school.db.tables.MEDICAL_AID_PROVIDER;
import zw.co.elearning.school.db.tables.MEDICAL_PROCEDURE;
import zw.co.elearning.school.db.tables.NURSE_GENERAL_EXAMINATION;
import zw.co.elearning.school.db.tables.NURSE_VAGINAL_EXAMINATION;
import zw.co.elearning.school.db.tables.OBSTETRIC_EXAMINATION;
import zw.co.elearning.school.db.tables.OBSTRETRIC_EXAMINATION;
import zw.co.elearning.school.db.tables.OCCUPATION;
import zw.co.elearning.school.db.tables.OPD;
import zw.co.elearning.school.db.tables.OPD_ENCOUNTER;
import zw.co.elearning.school.db.tables.OPD_QUEUE;
import zw.co.elearning.school.db.tables.PERINIUM_REPAIR_TYPE;
import zw.co.elearning.school.db.tables.PERSON;
import zw.co.elearning.school.db.tables.PERSON_ALLERGY;
import zw.co.elearning.school.db.tables.PERSON_ART_FOLLOW_UP_STATUS;
import zw.co.elearning.school.db.tables.PERSON_ART_FUNCTIONAL_STATUS;
import zw.co.elearning.school.db.tables.PERSON_ART_IPT_STATUS;
import zw.co.elearning.school.db.tables.PERSON_ART_REGIMEN;
import zw.co.elearning.school.db.tables.PERSON_ART_STATUS;
import zw.co.elearning.school.db.tables.PERSON_ART_WHO_STAGE;
import zw.co.elearning.school.db.tables.PERSON_COMPLAINT;
import zw.co.elearning.school.db.tables.PERSON_DIAGNOSIS;
import zw.co.elearning.school.db.tables.PERSON_EXAMINATION;
import zw.co.elearning.school.db.tables.PERSON_HEALTH_EDUCATION;
import zw.co.elearning.school.db.tables.PERSON_ID;
import zw.co.elearning.school.db.tables.PERSON_IDENTIFIER;
import zw.co.elearning.school.db.tables.PERSON_INVESTIGATION;
import zw.co.elearning.school.db.tables.PERSON_INVESTIGATION_TEST;
import zw.co.elearning.school.db.tables.PERSON_MEDICATION;
import zw.co.elearning.school.db.tables.PERSON_PROCEDURE;
import zw.co.elearning.school.db.tables.PERSON_VITAL;
import zw.co.elearning.school.db.tables.PHONE;
import zw.co.elearning.school.db.tables.PLACENTA_AND_MEMBRANE;
import zw.co.elearning.school.db.tables.PLACENTA_DELIVERY_TYPE;
import zw.co.elearning.school.db.tables.PNC;
import zw.co.elearning.school.db.tables.PNC_CHILD;
import zw.co.elearning.school.db.tables.PNC_PROPERTY;
import zw.co.elearning.school.db.tables.PNC_QUESTIONARE;
import zw.co.elearning.school.db.tables.PNC_QUESTIONARE_CATEGORY;
import zw.co.elearning.school.db.tables.PNC_VISIT;
import zw.co.elearning.school.db.tables.PNC_VISIT_TYPE;
import zw.co.elearning.school.db.tables.PRESCRIPTION;
import zw.co.elearning.school.db.tables.PROVINCE;
import zw.co.elearning.school.db.tables.PURPOSE_OF_TEST;
import zw.co.elearning.school.db.tables.QUEUE;
import zw.co.elearning.school.db.tables.REASON_FOR_NOT_ISSUING_RESULT;
import zw.co.elearning.school.db.tables.REFERRAL;
import zw.co.elearning.school.db.tables.REFERRAL_REASON;
import zw.co.elearning.school.db.tables.RELATION;
import zw.co.elearning.school.db.tables.RELATIONSHIP_TYPE;
import zw.co.elearning.school.db.tables.SAMPLE;
import zw.co.elearning.school.db.tables.SITE_SETTING;
import zw.co.elearning.school.db.tables.STAGE;
import zw.co.elearning.school.db.tables.STAGE_NUMBER;
import zw.co.elearning.school.db.tables.STANDARD;
import zw.co.elearning.school.db.tables.SUPPLIER;
import zw.co.elearning.school.db.tables.TB;
import zw.co.elearning.school.db.tables.TB_CATEGORY;
import zw.co.elearning.school.db.tables.TB_QUESTIONARE;
import zw.co.elearning.school.db.tables.TB_RISK_GROUP;
import zw.co.elearning.school.db.tables.TB_STATUS;
import zw.co.elearning.school.db.tables.TB_SURVEY;
import zw.co.elearning.school.db.tables.TB_VISIT;
import zw.co.elearning.school.db.tables.TEST_KIT;
import zw.co.elearning.school.db.tables.TEST_KIT_BATCH;
import zw.co.elearning.school.db.tables.TOWN;
import zw.co.elearning.school.db.tables.UNIT;
import zw.co.elearning.school.db.tables.VAGINAL_MONITORING;
import zw.co.elearning.school.db.tables.VITAL;
import zw.co.elearning.school.db.tables.WARD;
import zw.co.elearning.school.db.tables.ZEPI_DRUG_NAME;


/**
 * Convenience access to all tables in school
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>school.address</code>.
     */
    public static final ADDRESS ADDRESS = zw.co.elearning.school.db.tables.ADDRESS.ADDRESS;

    /**
     * The table <code>school.admission</code>.
     */
    public static final ADMISSION ADMISSION = zw.co.elearning.school.db.tables.ADMISSION.ADMISSION;

    /**
     * The table <code>school.admission_encounter</code>.
     */
    public static final ADMISSION_ENCOUNTER ADMISSION_ENCOUNTER = zw.co.elearning.school.db.tables.ADMISSION_ENCOUNTER.ADMISSION_ENCOUNTER;

    /**
     * The table <code>school.allergy</code>.
     */
    public static final ALLERGY ALLERGY = zw.co.elearning.school.db.tables.ALLERGY.ALLERGY;

    /**
     * The table <code>school.amniotic_fluid</code>.
     */
    public static final AMNIOTIC_FLUID AMNIOTIC_FLUID = zw.co.elearning.school.db.tables.AMNIOTIC_FLUID.AMNIOTIC_FLUID;

    /**
     * The table <code>school.anc</code>.
     */
    public static final ANC ANC = zw.co.elearning.school.db.tables.ANC.ANC;

    /**
     * The table <code>school.anc_history</code>.
     */
    public static final ANC_HISTORY ANC_HISTORY = zw.co.elearning.school.db.tables.ANC_HISTORY.ANC_HISTORY;

    /**
     * The table <code>school.anc_questionare</code>.
     */
    public static final ANC_QUESTIONARE ANC_QUESTIONARE = zw.co.elearning.school.db.tables.ANC_QUESTIONARE.ANC_QUESTIONARE;

    /**
     * The table <code>school.anc_visit</code>.
     */
    public static final ANC_VISIT ANC_VISIT = zw.co.elearning.school.db.tables.ANC_VISIT.ANC_VISIT;

    /**
     * The table <code>school.appointment</code>.
     */
    public static final APPOINTMENT APPOINTMENT = zw.co.elearning.school.db.tables.APPOINTMENT.APPOINTMENT;

    /**
     * The table <code>school.appointment_cancellation_reason</code>.
     */
    public static final APPOINTMENT_CANCELLATION_REASON APPOINTMENT_CANCELLATION_REASON = zw.co.elearning.school.db.tables.APPOINTMENT_CANCELLATION_REASON.APPOINTMENT_CANCELLATION_REASON;

    /**
     * The table <code>school.appointment_reason</code>.
     */
    public static final APPOINTMENT_REASON APPOINTMENT_REASON = zw.co.elearning.school.db.tables.APPOINTMENT_REASON.APPOINTMENT_REASON;

    /**
     * The table <code>school.appointment_reschedulling_reason</code>.
     */
    public static final APPOINTMENT_RESCHEDULLING_REASON APPOINTMENT_RESCHEDULLING_REASON = zw.co.elearning.school.db.tables.APPOINTMENT_RESCHEDULLING_REASON.APPOINTMENT_RESCHEDULLING_REASON;

    /**
     * The table <code>school.art</code>.
     */
    public static final ART ART = zw.co.elearning.school.db.tables.ART.ART;

    /**
     * The table <code>school.art_current_sign</code>.
     */
    public static final ART_CURRENT_SIGN ART_CURRENT_SIGN = zw.co.elearning.school.db.tables.ART_CURRENT_SIGN.ART_CURRENT_SIGN;

    /**
     * The table <code>school.art_current_symptom</code>.
     */
    public static final ART_CURRENT_SYMPTOM ART_CURRENT_SYMPTOM = zw.co.elearning.school.db.tables.ART_CURRENT_SYMPTOM.ART_CURRENT_SYMPTOM;

    /**
     * The table <code>school.art_investigation_history</code>.
     */
    public static final ART_INVESTIGATION_HISTORY ART_INVESTIGATION_HISTORY = zw.co.elearning.school.db.tables.ART_INVESTIGATION_HISTORY.ART_INVESTIGATION_HISTORY;

    /**
     * The table <code>school.art_medical_history</code>.
     */
    public static final ART_MEDICAL_HISTORY ART_MEDICAL_HISTORY = zw.co.elearning.school.db.tables.ART_MEDICAL_HISTORY.ART_MEDICAL_HISTORY;

    /**
     * The table <code>school.art_medication_history</code>.
     */
    public static final ART_MEDICATION_HISTORY ART_MEDICATION_HISTORY = zw.co.elearning.school.db.tables.ART_MEDICATION_HISTORY.ART_MEDICATION_HISTORY;

    /**
     * The table <code>school.art_questionare</code>.
     */
    public static final ART_QUESTIONARE ART_QUESTIONARE = zw.co.elearning.school.db.tables.ART_QUESTIONARE.ART_QUESTIONARE;

    /**
     * The table <code>school.art_reason</code>.
     */
    public static final ART_REASON ART_REASON = zw.co.elearning.school.db.tables.ART_REASON.ART_REASON;

    /**
     * The table <code>school.art_status</code>.
     */
    public static final ART_STATUS ART_STATUS = zw.co.elearning.school.db.tables.ART_STATUS.ART_STATUS;

    /**
     * The table <code>school.art_visit</code>.
     */
    public static final ART_VISIT ART_VISIT = zw.co.elearning.school.db.tables.ART_VISIT.ART_VISIT;

    /**
     * The table <code>school.art_visit_new_oi</code>.
     */
    public static final ART_VISIT_NEW_OI ART_VISIT_NEW_OI = zw.co.elearning.school.db.tables.ART_VISIT_NEW_OI.ART_VISIT_NEW_OI;

    /**
     * The table <code>school.art_visit_status</code>.
     */
    public static final ART_VISIT_STATUS ART_VISIT_STATUS = zw.co.elearning.school.db.tables.ART_VISIT_STATUS.ART_VISIT_STATUS;

    /**
     * The table <code>school.art_visit_type</code>.
     */
    public static final ART_VISIT_TYPE ART_VISIT_TYPE = zw.co.elearning.school.db.tables.ART_VISIT_TYPE.ART_VISIT_TYPE;

    /**
     * The table <code>school.arv_combination_regimen</code>.
     */
    public static final ARV_COMBINATION_REGIMEN ARV_COMBINATION_REGIMEN = zw.co.elearning.school.db.tables.ARV_COMBINATION_REGIMEN.ARV_COMBINATION_REGIMEN;

    /**
     * The table <code>school.cervix</code>.
     */
    public static final CERVIX CERVIX = zw.co.elearning.school.db.tables.CERVIX.CERVIX;

    /**
     * The table <code>school.complaint</code>.
     */
    public static final COMPLAINT COMPLAINT = zw.co.elearning.school.db.tables.COMPLAINT.COMPLAINT;

    /**
     * The table <code>school.contraction</code>.
     */
    public static final CONTRACTION CONTRACTION = zw.co.elearning.school.db.tables.CONTRACTION.CONTRACTION;

    /**
     * The table <code>school.degree</code>.
     */
    public static final DEGREE DEGREE = zw.co.elearning.school.db.tables.DEGREE.DEGREE;

    /**
     * The table <code>school.degree_of_moulding</code>.
     */
    public static final DEGREE_OF_MOULDING DEGREE_OF_MOULDING = zw.co.elearning.school.db.tables.DEGREE_OF_MOULDING.DEGREE_OF_MOULDING;

    /**
     * The table <code>school.delivery</code>.
     */
    public static final DELIVERY DELIVERY = zw.co.elearning.school.db.tables.DELIVERY.DELIVERY;

    /**
     * The table <code>school.delivery_history</code>.
     */
    public static final DELIVERY_HISTORY DELIVERY_HISTORY = zw.co.elearning.school.db.tables.DELIVERY_HISTORY.DELIVERY_HISTORY;

    /**
     * The table <code>school.delivery_maternal_death_factor</code>.
     */
    public static final DELIVERY_MATERNAL_DEATH_FACTOR DELIVERY_MATERNAL_DEATH_FACTOR = zw.co.elearning.school.db.tables.DELIVERY_MATERNAL_DEATH_FACTOR.DELIVERY_MATERNAL_DEATH_FACTOR;

    /**
     * The table <code>school.delivery_partogram</code>.
     */
    public static final DELIVERY_PARTOGRAM DELIVERY_PARTOGRAM = zw.co.elearning.school.db.tables.DELIVERY_PARTOGRAM.DELIVERY_PARTOGRAM;

    /**
     * The table <code>school.delivery_questionare</code>.
     */
    public static final DELIVERY_QUESTIONARE DELIVERY_QUESTIONARE = zw.co.elearning.school.db.tables.DELIVERY_QUESTIONARE.DELIVERY_QUESTIONARE;

    /**
     * The table <code>school.delivery_summary</code>.
     */
    public static final DELIVERY_SUMMARY DELIVERY_SUMMARY = zw.co.elearning.school.db.tables.DELIVERY_SUMMARY.DELIVERY_SUMMARY;

    /**
     * The table <code>school.delivery_type</code>.
     */
    public static final DELIVERY_TYPE DELIVERY_TYPE = zw.co.elearning.school.db.tables.DELIVERY_TYPE.DELIVERY_TYPE;

    /**
     * The table <code>school.department</code>.
     */
    public static final DEPARTMENT DEPARTMENT = zw.co.elearning.school.db.tables.DEPARTMENT.DEPARTMENT;

    /**
     * The table <code>school.diagnosis</code>.
     */
    public static final DIAGNOSIS DIAGNOSIS = zw.co.elearning.school.db.tables.DIAGNOSIS.DIAGNOSIS;

    /**
     * The table <code>school.dispense</code>.
     */
    public static final DISPENSE DISPENSE = zw.co.elearning.school.db.tables.DISPENSE.DISPENSE;

    /**
     * The table <code>school.district</code>.
     */
    public static final DISTRICT DISTRICT = zw.co.elearning.school.db.tables.DISTRICT.DISTRICT;

    /**
     * The table <code>school.doctor_general_examination</code>.
     */
    public static final DOCTOR_GENERAL_EXAMINATION DOCTOR_GENERAL_EXAMINATION = zw.co.elearning.school.db.tables.DOCTOR_GENERAL_EXAMINATION.DOCTOR_GENERAL_EXAMINATION;

    /**
     * The table <code>school.doctor_vaginal_examination</code>.
     */
    public static final DOCTOR_VAGINAL_EXAMINATION DOCTOR_VAGINAL_EXAMINATION = zw.co.elearning.school.db.tables.DOCTOR_VAGINAL_EXAMINATION.DOCTOR_VAGINAL_EXAMINATION;

    /**
     * The table <code>school.drug</code>.
     */
    public static final DRUG DRUG = zw.co.elearning.school.db.tables.DRUG.DRUG;

    /**
     * The table <code>school.drug_batch</code>.
     */
    public static final DRUG_BATCH DRUG_BATCH = zw.co.elearning.school.db.tables.DRUG_BATCH.DRUG_BATCH;

    /**
     * The table <code>school.drug_name</code>.
     */
    public static final DRUG_NAME DRUG_NAME = zw.co.elearning.school.db.tables.DRUG_NAME.DRUG_NAME;

    /**
     * The table <code>school.drug_option</code>.
     */
    public static final DRUG_OPTION DRUG_OPTION = zw.co.elearning.school.db.tables.DRUG_OPTION.DRUG_OPTION;

    /**
     * The table <code>school.drug_suffix</code>.
     */
    public static final DRUG_SUFFIX DRUG_SUFFIX = zw.co.elearning.school.db.tables.DRUG_SUFFIX.DRUG_SUFFIX;

    /**
     * The table <code>school.education_level</code>.
     */
    public static final EDUCATION_LEVEL EDUCATION_LEVEL = zw.co.elearning.school.db.tables.EDUCATION_LEVEL.EDUCATION_LEVEL;

    /**
     * The table <code>school.email</code>.
     */
    public static final EMAIL EMAIL = zw.co.elearning.school.db.tables.EMAIL.EMAIL;

    /**
     * The table <code>school.encounter</code>.
     */
    public static final ENCOUNTER ENCOUNTER = zw.co.elearning.school.db.tables.ENCOUNTER.ENCOUNTER;

    /**
     * The table <code>school.encounter_complaint</code>.
     */
    public static final ENCOUNTER_COMPLAINT ENCOUNTER_COMPLAINT = zw.co.elearning.school.db.tables.ENCOUNTER_COMPLAINT.ENCOUNTER_COMPLAINT;

    /**
     * The table <code>school.encounter_diagnosis</code>.
     */
    public static final ENCOUNTER_DIAGNOSIS ENCOUNTER_DIAGNOSIS = zw.co.elearning.school.db.tables.ENCOUNTER_DIAGNOSIS.ENCOUNTER_DIAGNOSIS;

    /**
     * The table <code>school.encounter_examination</code>.
     */
    public static final ENCOUNTER_EXAMINATION ENCOUNTER_EXAMINATION = zw.co.elearning.school.db.tables.ENCOUNTER_EXAMINATION.ENCOUNTER_EXAMINATION;

    /**
     * The table <code>school.encounter_health_education</code>.
     */
    public static final ENCOUNTER_HEALTH_EDUCATION ENCOUNTER_HEALTH_EDUCATION = zw.co.elearning.school.db.tables.ENCOUNTER_HEALTH_EDUCATION.ENCOUNTER_HEALTH_EDUCATION;

    /**
     * The table <code>school.encounter_investigation</code>.
     */
    public static final ENCOUNTER_INVESTIGATION ENCOUNTER_INVESTIGATION = zw.co.elearning.school.db.tables.ENCOUNTER_INVESTIGATION.ENCOUNTER_INVESTIGATION;

    /**
     * The table <code>school.encounter_medication</code>.
     */
    public static final ENCOUNTER_MEDICATION ENCOUNTER_MEDICATION = zw.co.elearning.school.db.tables.ENCOUNTER_MEDICATION.ENCOUNTER_MEDICATION;

    /**
     * The table <code>school.encounter_note</code>.
     */
    public static final ENCOUNTER_NOTE ENCOUNTER_NOTE = zw.co.elearning.school.db.tables.ENCOUNTER_NOTE.ENCOUNTER_NOTE;

    /**
     * The table <code>school.encounter_procedure</code>.
     */
    public static final ENCOUNTER_PROCEDURE ENCOUNTER_PROCEDURE = zw.co.elearning.school.db.tables.ENCOUNTER_PROCEDURE.ENCOUNTER_PROCEDURE;

    /**
     * The table <code>school.encounter_vital</code>.
     */
    public static final ENCOUNTER_VITAL ENCOUNTER_VITAL = zw.co.elearning.school.db.tables.ENCOUNTER_VITAL.ENCOUNTER_VITAL;

    /**
     * The table <code>school.examination</code>.
     */
    public static final EXAMINATION EXAMINATION = zw.co.elearning.school.db.tables.EXAMINATION.EXAMINATION;

    /**
     * The table <code>school.facility</code>.
     */
    public static final FACILITY FACILITY = zw.co.elearning.school.db.tables.FACILITY.FACILITY;

    /**
     * The table <code>school.family_planning_method</code>.
     */
    public static final FAMILY_PLANNING_METHOD FAMILY_PLANNING_METHOD = zw.co.elearning.school.db.tables.FAMILY_PLANNING_METHOD.FAMILY_PLANNING_METHOD;

    /**
     * The table <code>school.feeding_option</code>.
     */
    public static final FEEDING_OPTION FEEDING_OPTION = zw.co.elearning.school.db.tables.FEEDING_OPTION.FEEDING_OPTION;

    /**
     * The table <code>school.foetal_death</code>.
     */
    public static final FOETAL_DEATH FOETAL_DEATH = zw.co.elearning.school.db.tables.FOETAL_DEATH.FOETAL_DEATH;

    /**
     * The table <code>school.follow_up_status</code>.
     */
    public static final FOLLOW_UP_STATUS FOLLOW_UP_STATUS = zw.co.elearning.school.db.tables.FOLLOW_UP_STATUS.FOLLOW_UP_STATUS;

    /**
     * The table <code>school.formulation</code>.
     */
    public static final FORMULATION FORMULATION = zw.co.elearning.school.db.tables.FORMULATION.FORMULATION;

    /**
     * The table <code>school.frequency</code>.
     */
    public static final FREQUENCY FREQUENCY = zw.co.elearning.school.db.tables.FREQUENCY.FREQUENCY;

    /**
     * The table <code>school.functional_status</code>.
     */
    public static final FUNCTIONAL_STATUS FUNCTIONAL_STATUS = zw.co.elearning.school.db.tables.FUNCTIONAL_STATUS.FUNCTIONAL_STATUS;

    /**
     * The table <code>school.general_assessment</code>.
     */
    public static final GENERAL_ASSESSMENT GENERAL_ASSESSMENT = zw.co.elearning.school.db.tables.GENERAL_ASSESSMENT.GENERAL_ASSESSMENT;

    /**
     * The table <code>school.health_education_topic</code>.
     */
    public static final HEALTH_EDUCATION_TOPIC HEALTH_EDUCATION_TOPIC = zw.co.elearning.school.db.tables.HEALTH_EDUCATION_TOPIC.HEALTH_EDUCATION_TOPIC;

    /**
     * The table <code>school.hibernate_sequence</code>.
     */
    public static final HIBERNATE_SEQUENCE HIBERNATE_SEQUENCE = zw.co.elearning.school.db.tables.HIBERNATE_SEQUENCE.HIBERNATE_SEQUENCE;

    /**
     * The table <code>school.hts</code>.
     */
    public static final HTS HTS = zw.co.elearning.school.db.tables.HTS.HTS;

    /**
     * The table <code>school.hts_model</code>.
     */
    public static final HTS_MODEL HTS_MODEL = zw.co.elearning.school.db.tables.HTS_MODEL.HTS_MODEL;

    /**
     * The table <code>school.hts_post_test_service</code>.
     */
    public static final HTS_POST_TEST_SERVICE HTS_POST_TEST_SERVICE = zw.co.elearning.school.db.tables.HTS_POST_TEST_SERVICE.HTS_POST_TEST_SERVICE;

    /**
     * The table <code>school.hts_post_test_service_offered</code>.
     */
    public static final HTS_POST_TEST_SERVICE_OFFERED HTS_POST_TEST_SERVICE_OFFERED = zw.co.elearning.school.db.tables.HTS_POST_TEST_SERVICE_OFFERED.HTS_POST_TEST_SERVICE_OFFERED;

    /**
     * The table <code>school.immunization_schedule</code>.
     */
    public static final IMMUNIZATION_SCHEDULE IMMUNIZATION_SCHEDULE = zw.co.elearning.school.db.tables.IMMUNIZATION_SCHEDULE.IMMUNIZATION_SCHEDULE;

    /**
     * The table <code>school.imnci_category</code>.
     */
    public static final IMNCI_CATEGORY IMNCI_CATEGORY = zw.co.elearning.school.db.tables.IMNCI_CATEGORY.IMNCI_CATEGORY;

    /**
     * The table <code>school.imnci_classification</code>.
     */
    public static final IMNCI_CLASSIFICATION IMNCI_CLASSIFICATION = zw.co.elearning.school.db.tables.IMNCI_CLASSIFICATION.IMNCI_CLASSIFICATION;

    /**
     * The table <code>school.imnci_questionnaire</code>.
     */
    public static final IMNCI_QUESTIONNAIRE IMNCI_QUESTIONNAIRE = zw.co.elearning.school.db.tables.IMNCI_QUESTIONNAIRE.IMNCI_QUESTIONNAIRE;

    /**
     * The table <code>school.imnci_visit</code>.
     */
    public static final IMNCI_VISIT IMNCI_VISIT = zw.co.elearning.school.db.tables.IMNCI_VISIT.IMNCI_VISIT;

    /**
     * The table <code>school.imnci_visit_question</code>.
     */
    public static final IMNCI_VISIT_QUESTION IMNCI_VISIT_QUESTION = zw.co.elearning.school.db.tables.IMNCI_VISIT_QUESTION.IMNCI_VISIT_QUESTION;

    /**
     * The table <code>school.infant</code>.
     */
    public static final INFANT INFANT = zw.co.elearning.school.db.tables.INFANT.INFANT;

    /**
     * The table <code>school.investigation</code>.
     */
    public static final INVESTIGATION INVESTIGATION = zw.co.elearning.school.db.tables.INVESTIGATION.INVESTIGATION;

    /**
     * The table <code>school.investigation_history</code>.
     */
    public static final INVESTIGATION_HISTORY INVESTIGATION_HISTORY = zw.co.elearning.school.db.tables.INVESTIGATION_HISTORY.INVESTIGATION_HISTORY;

    /**
     * The table <code>school.investigation_result</code>.
     */
    public static final INVESTIGATION_RESULT INVESTIGATION_RESULT = zw.co.elearning.school.db.tables.INVESTIGATION_RESULT.INVESTIGATION_RESULT;

    /**
     * The table <code>school.investigation_result_diagnoses</code>.
     */
    public static final INVESTIGATION_RESULT_DIAGNOSES INVESTIGATION_RESULT_DIAGNOSES = zw.co.elearning.school.db.tables.INVESTIGATION_RESULT_DIAGNOSES.INVESTIGATION_RESULT_DIAGNOSES;

    /**
     * The table <code>school.investigation_test_kit</code>.
     */
    public static final INVESTIGATION_TEST_KIT INVESTIGATION_TEST_KIT = zw.co.elearning.school.db.tables.INVESTIGATION_TEST_KIT.INVESTIGATION_TEST_KIT;

    /**
     * The table <code>school.ipt_reason</code>.
     */
    public static final IPT_REASON IPT_REASON = zw.co.elearning.school.db.tables.IPT_REASON.IPT_REASON;

    /**
     * The table <code>school.ipt_status</code>.
     */
    public static final IPT_STATUS IPT_STATUS = zw.co.elearning.school.db.tables.IPT_STATUS.IPT_STATUS;

    /**
     * The table <code>school.jhi_authority</code>.
     */
    public static final JHI_AUTHORITY JHI_AUTHORITY = zw.co.elearning.school.db.tables.JHI_AUTHORITY.JHI_AUTHORITY;

    /**
     * The table <code>school.jhi_entity_audit_event</code>.
     */
    public static final JHI_ENTITY_AUDIT_EVENT JHI_ENTITY_AUDIT_EVENT = zw.co.elearning.school.db.tables.JHI_ENTITY_AUDIT_EVENT.JHI_ENTITY_AUDIT_EVENT;

    /**
     * The table <code>school.jhi_persistent_audit_event</code>.
     */
    public static final JHI_PERSISTENT_AUDIT_EVENT JHI_PERSISTENT_AUDIT_EVENT = zw.co.elearning.school.db.tables.JHI_PERSISTENT_AUDIT_EVENT.JHI_PERSISTENT_AUDIT_EVENT;

    /**
     * The table <code>school.jhi_persistent_audit_evt_data</code>.
     */
    public static final JHI_PERSISTENT_AUDIT_EVT_DATA JHI_PERSISTENT_AUDIT_EVT_DATA = zw.co.elearning.school.db.tables.JHI_PERSISTENT_AUDIT_EVT_DATA.JHI_PERSISTENT_AUDIT_EVT_DATA;

    /**
     * The table <code>school.jhi_user</code>.
     */
    public static final JHI_USER JHI_USER = zw.co.elearning.school.db.tables.JHI_USER.JHI_USER;

    /**
     * The table <code>school.jhi_user_authority</code>.
     */
    public static final JHI_USER_AUTHORITY JHI_USER_AUTHORITY = zw.co.elearning.school.db.tables.JHI_USER_AUTHORITY.JHI_USER_AUTHORITY;

    /**
     * The table <code>school.laboratory</code>.
     */
    public static final LABORATORY LABORATORY = zw.co.elearning.school.db.tables.LABORATORY.LABORATORY;

    /**
     * The table <code>school.labour_summary</code>.
     */
    public static final LABOUR_SUMMARY LABOUR_SUMMARY = zw.co.elearning.school.db.tables.LABOUR_SUMMARY.LABOUR_SUMMARY;

    /**
     * The table <code>school.lab_result</code>.
     */
    public static final LAB_RESULT LAB_RESULT = zw.co.elearning.school.db.tables.LAB_RESULT.LAB_RESULT;

    /**
     * The table <code>school.lab_test</code>.
     */
    public static final LAB_TEST LAB_TEST = zw.co.elearning.school.db.tables.LAB_TEST.LAB_TEST;

    /**
     * The table <code>school.level_of_presenting_part</code>.
     */
    public static final LEVEL_OF_PRESENTING_PART LEVEL_OF_PRESENTING_PART = zw.co.elearning.school.db.tables.LEVEL_OF_PRESENTING_PART.LEVEL_OF_PRESENTING_PART;

    /**
     * The table <code>school.marital_state</code>.
     */
    public static final MARITAL_STATE MARITAL_STATE = zw.co.elearning.school.db.tables.MARITAL_STATE.MARITAL_STATE;

    /**
     * The table <code>school.maternal_death</code>.
     */
    public static final MATERNAL_DEATH MATERNAL_DEATH = zw.co.elearning.school.db.tables.MATERNAL_DEATH.MATERNAL_DEATH;

    /**
     * The table <code>school.maternal_death_factor</code>.
     */
    public static final MATERNAL_DEATH_FACTOR MATERNAL_DEATH_FACTOR = zw.co.elearning.school.db.tables.MATERNAL_DEATH_FACTOR.MATERNAL_DEATH_FACTOR;

    /**
     * The table <code>school.medical_aid</code>.
     */
    public static final MEDICAL_AID MEDICAL_AID = zw.co.elearning.school.db.tables.MEDICAL_AID.MEDICAL_AID;

    /**
     * The table <code>school.medical_aid_provider</code>.
     */
    public static final MEDICAL_AID_PROVIDER MEDICAL_AID_PROVIDER = zw.co.elearning.school.db.tables.MEDICAL_AID_PROVIDER.MEDICAL_AID_PROVIDER;

    /**
     * The table <code>school.medical_procedure</code>.
     */
    public static final MEDICAL_PROCEDURE MEDICAL_PROCEDURE = zw.co.elearning.school.db.tables.MEDICAL_PROCEDURE.MEDICAL_PROCEDURE;

    /**
     * The table <code>school.nurse_general_examination</code>.
     */
    public static final NURSE_GENERAL_EXAMINATION NURSE_GENERAL_EXAMINATION = zw.co.elearning.school.db.tables.NURSE_GENERAL_EXAMINATION.NURSE_GENERAL_EXAMINATION;

    /**
     * The table <code>school.nurse_vaginal_examination</code>.
     */
    public static final NURSE_VAGINAL_EXAMINATION NURSE_VAGINAL_EXAMINATION = zw.co.elearning.school.db.tables.NURSE_VAGINAL_EXAMINATION.NURSE_VAGINAL_EXAMINATION;

    /**
     * The table <code>school.obstetric_examination</code>.
     */
    public static final OBSTETRIC_EXAMINATION OBSTETRIC_EXAMINATION = zw.co.elearning.school.db.tables.OBSTETRIC_EXAMINATION.OBSTETRIC_EXAMINATION;

    /**
     * The table <code>school.obstretric_examination</code>.
     */
    public static final OBSTRETRIC_EXAMINATION OBSTRETRIC_EXAMINATION = zw.co.elearning.school.db.tables.OBSTRETRIC_EXAMINATION.OBSTRETRIC_EXAMINATION;

    /**
     * The table <code>school.occupation</code>.
     */
    public static final OCCUPATION OCCUPATION = zw.co.elearning.school.db.tables.OCCUPATION.OCCUPATION;

    /**
     * The table <code>school.opd</code>.
     */
    public static final OPD OPD = zw.co.elearning.school.db.tables.OPD.OPD;

    /**
     * The table <code>school.opd_encounter</code>.
     */
    public static final OPD_ENCOUNTER OPD_ENCOUNTER = zw.co.elearning.school.db.tables.OPD_ENCOUNTER.OPD_ENCOUNTER;

    /**
     * The table <code>school.opd_queue</code>.
     */
    public static final OPD_QUEUE OPD_QUEUE = zw.co.elearning.school.db.tables.OPD_QUEUE.OPD_QUEUE;

    /**
     * The table <code>school.perinium_repair_type</code>.
     */
    public static final PERINIUM_REPAIR_TYPE PERINIUM_REPAIR_TYPE = zw.co.elearning.school.db.tables.PERINIUM_REPAIR_TYPE.PERINIUM_REPAIR_TYPE;

    /**
     * The table <code>school.person</code>.
     */
    public static final PERSON PERSON = zw.co.elearning.school.db.tables.PERSON.PERSON;

    /**
     * The table <code>school.person_allergy</code>.
     */
    public static final PERSON_ALLERGY PERSON_ALLERGY = zw.co.elearning.school.db.tables.PERSON_ALLERGY.PERSON_ALLERGY;

    /**
     * The table <code>school.person_art_follow_up_status</code>.
     */
    public static final PERSON_ART_FOLLOW_UP_STATUS PERSON_ART_FOLLOW_UP_STATUS = zw.co.elearning.school.db.tables.PERSON_ART_FOLLOW_UP_STATUS.PERSON_ART_FOLLOW_UP_STATUS;

    /**
     * The table <code>school.person_art_functional_status</code>.
     */
    public static final PERSON_ART_FUNCTIONAL_STATUS PERSON_ART_FUNCTIONAL_STATUS = zw.co.elearning.school.db.tables.PERSON_ART_FUNCTIONAL_STATUS.PERSON_ART_FUNCTIONAL_STATUS;

    /**
     * The table <code>school.person_art_ipt_status</code>.
     */
    public static final PERSON_ART_IPT_STATUS PERSON_ART_IPT_STATUS = zw.co.elearning.school.db.tables.PERSON_ART_IPT_STATUS.PERSON_ART_IPT_STATUS;

    /**
     * The table <code>school.person_art_regimen</code>.
     */
    public static final PERSON_ART_REGIMEN PERSON_ART_REGIMEN = zw.co.elearning.school.db.tables.PERSON_ART_REGIMEN.PERSON_ART_REGIMEN;

    /**
     * The table <code>school.person_art_status</code>.
     */
    public static final PERSON_ART_STATUS PERSON_ART_STATUS = zw.co.elearning.school.db.tables.PERSON_ART_STATUS.PERSON_ART_STATUS;

    /**
     * The table <code>school.person_art_who_stage</code>.
     */
    public static final PERSON_ART_WHO_STAGE PERSON_ART_WHO_STAGE = zw.co.elearning.school.db.tables.PERSON_ART_WHO_STAGE.PERSON_ART_WHO_STAGE;

    /**
     * The table <code>school.person_complaint</code>.
     */
    public static final PERSON_COMPLAINT PERSON_COMPLAINT = zw.co.elearning.school.db.tables.PERSON_COMPLAINT.PERSON_COMPLAINT;

    /**
     * The table <code>school.person_diagnosis</code>.
     */
    public static final PERSON_DIAGNOSIS PERSON_DIAGNOSIS = zw.co.elearning.school.db.tables.PERSON_DIAGNOSIS.PERSON_DIAGNOSIS;

    /**
     * The table <code>school.person_examination</code>.
     */
    public static final PERSON_EXAMINATION PERSON_EXAMINATION = zw.co.elearning.school.db.tables.PERSON_EXAMINATION.PERSON_EXAMINATION;

    /**
     * The table <code>school.person_health_education</code>.
     */
    public static final PERSON_HEALTH_EDUCATION PERSON_HEALTH_EDUCATION = zw.co.elearning.school.db.tables.PERSON_HEALTH_EDUCATION.PERSON_HEALTH_EDUCATION;

    /**
     * The table <code>school.person_id</code>.
     */
    public static final PERSON_ID PERSON_ID = zw.co.elearning.school.db.tables.PERSON_ID.PERSON_ID;

    /**
     * The table <code>school.person_identifier</code>.
     */
    public static final PERSON_IDENTIFIER PERSON_IDENTIFIER = zw.co.elearning.school.db.tables.PERSON_IDENTIFIER.PERSON_IDENTIFIER;

    /**
     * The table <code>school.person_investigation</code>.
     */
    public static final PERSON_INVESTIGATION PERSON_INVESTIGATION = zw.co.elearning.school.db.tables.PERSON_INVESTIGATION.PERSON_INVESTIGATION;

    /**
     * The table <code>school.person_investigation_test</code>.
     */
    public static final PERSON_INVESTIGATION_TEST PERSON_INVESTIGATION_TEST = zw.co.elearning.school.db.tables.PERSON_INVESTIGATION_TEST.PERSON_INVESTIGATION_TEST;

    /**
     * The table <code>school.person_medication</code>.
     */
    public static final PERSON_MEDICATION PERSON_MEDICATION = zw.co.elearning.school.db.tables.PERSON_MEDICATION.PERSON_MEDICATION;

    /**
     * The table <code>school.person_procedure</code>.
     */
    public static final PERSON_PROCEDURE PERSON_PROCEDURE = zw.co.elearning.school.db.tables.PERSON_PROCEDURE.PERSON_PROCEDURE;

    /**
     * The table <code>school.person_vital</code>.
     */
    public static final PERSON_VITAL PERSON_VITAL = zw.co.elearning.school.db.tables.PERSON_VITAL.PERSON_VITAL;

    /**
     * The table <code>school.phone</code>.
     */
    public static final PHONE PHONE = zw.co.elearning.school.db.tables.PHONE.PHONE;

    /**
     * The table <code>school.placenta_and_membrane</code>.
     */
    public static final PLACENTA_AND_MEMBRANE PLACENTA_AND_MEMBRANE = zw.co.elearning.school.db.tables.PLACENTA_AND_MEMBRANE.PLACENTA_AND_MEMBRANE;

    /**
     * The table <code>school.placenta_delivery_type</code>.
     */
    public static final PLACENTA_DELIVERY_TYPE PLACENTA_DELIVERY_TYPE = zw.co.elearning.school.db.tables.PLACENTA_DELIVERY_TYPE.PLACENTA_DELIVERY_TYPE;

    /**
     * The table <code>school.pnc</code>.
     */
    public static final PNC PNC = zw.co.elearning.school.db.tables.PNC.PNC;

    /**
     * The table <code>school.pnc_child</code>.
     */
    public static final PNC_CHILD PNC_CHILD = zw.co.elearning.school.db.tables.PNC_CHILD.PNC_CHILD;

    /**
     * The table <code>school.pnc_property</code>.
     */
    public static final PNC_PROPERTY PNC_PROPERTY = zw.co.elearning.school.db.tables.PNC_PROPERTY.PNC_PROPERTY;

    /**
     * The table <code>school.pnc_questionare</code>.
     */
    public static final PNC_QUESTIONARE PNC_QUESTIONARE = zw.co.elearning.school.db.tables.PNC_QUESTIONARE.PNC_QUESTIONARE;

    /**
     * The table <code>school.pnc_questionare_category</code>.
     */
    public static final PNC_QUESTIONARE_CATEGORY PNC_QUESTIONARE_CATEGORY = zw.co.elearning.school.db.tables.PNC_QUESTIONARE_CATEGORY.PNC_QUESTIONARE_CATEGORY;

    /**
     * The table <code>school.pnc_visit</code>.
     */
    public static final PNC_VISIT PNC_VISIT = zw.co.elearning.school.db.tables.PNC_VISIT.PNC_VISIT;

    /**
     * The table <code>school.pnc_visit_type</code>.
     */
    public static final PNC_VISIT_TYPE PNC_VISIT_TYPE = zw.co.elearning.school.db.tables.PNC_VISIT_TYPE.PNC_VISIT_TYPE;

    /**
     * The table <code>school.prescription</code>.
     */
    public static final PRESCRIPTION PRESCRIPTION = zw.co.elearning.school.db.tables.PRESCRIPTION.PRESCRIPTION;

    /**
     * The table <code>school.province</code>.
     */
    public static final PROVINCE PROVINCE = zw.co.elearning.school.db.tables.PROVINCE.PROVINCE;

    /**
     * The table <code>school.purpose_of_test</code>.
     */
    public static final PURPOSE_OF_TEST PURPOSE_OF_TEST = zw.co.elearning.school.db.tables.PURPOSE_OF_TEST.PURPOSE_OF_TEST;

    /**
     * The table <code>school.queue</code>.
     */
    public static final QUEUE QUEUE = zw.co.elearning.school.db.tables.QUEUE.QUEUE;

    /**
     * The table <code>school.reason_for_not_issuing_result</code>.
     */
    public static final REASON_FOR_NOT_ISSUING_RESULT REASON_FOR_NOT_ISSUING_RESULT = zw.co.elearning.school.db.tables.REASON_FOR_NOT_ISSUING_RESULT.REASON_FOR_NOT_ISSUING_RESULT;

    /**
     * The table <code>school.referral</code>.
     */
    public static final REFERRAL REFERRAL = zw.co.elearning.school.db.tables.REFERRAL.REFERRAL;

    /**
     * The table <code>school.referral_reason</code>.
     */
    public static final REFERRAL_REASON REFERRAL_REASON = zw.co.elearning.school.db.tables.REFERRAL_REASON.REFERRAL_REASON;

    /**
     * The table <code>school.relation</code>.
     */
    public static final RELATION RELATION = zw.co.elearning.school.db.tables.RELATION.RELATION;

    /**
     * The table <code>school.relationship_type</code>.
     */
    public static final RELATIONSHIP_TYPE RELATIONSHIP_TYPE = zw.co.elearning.school.db.tables.RELATIONSHIP_TYPE.RELATIONSHIP_TYPE;

    /**
     * The table <code>school.sample</code>.
     */
    public static final SAMPLE SAMPLE = zw.co.elearning.school.db.tables.SAMPLE.SAMPLE;

    /**
     * The table <code>school.site_setting</code>.
     */
    public static final SITE_SETTING SITE_SETTING = zw.co.elearning.school.db.tables.SITE_SETTING.SITE_SETTING;

    /**
     * The table <code>school.stage</code>.
     */
    public static final STAGE STAGE = zw.co.elearning.school.db.tables.STAGE.STAGE;

    /**
     * The table <code>school.stage_number</code>.
     */
    public static final STAGE_NUMBER STAGE_NUMBER = zw.co.elearning.school.db.tables.STAGE_NUMBER.STAGE_NUMBER;

    /**
     * The table <code>school.standard</code>.
     */
    public static final STANDARD STANDARD = zw.co.elearning.school.db.tables.STANDARD.STANDARD;

    /**
     * The table <code>school.supplier</code>.
     */
    public static final SUPPLIER SUPPLIER = zw.co.elearning.school.db.tables.SUPPLIER.SUPPLIER;

    /**
     * The table <code>school.tb</code>.
     */
    public static final TB TB = zw.co.elearning.school.db.tables.TB.TB;

    /**
     * The table <code>school.tb_category</code>.
     */
    public static final TB_CATEGORY TB_CATEGORY = zw.co.elearning.school.db.tables.TB_CATEGORY.TB_CATEGORY;

    /**
     * The table <code>school.tb_questionare</code>.
     */
    public static final TB_QUESTIONARE TB_QUESTIONARE = zw.co.elearning.school.db.tables.TB_QUESTIONARE.TB_QUESTIONARE;

    /**
     * The table <code>school.tb_risk_group</code>.
     */
    public static final TB_RISK_GROUP TB_RISK_GROUP = zw.co.elearning.school.db.tables.TB_RISK_GROUP.TB_RISK_GROUP;

    /**
     * The table <code>school.tb_status</code>.
     */
    public static final TB_STATUS TB_STATUS = zw.co.elearning.school.db.tables.TB_STATUS.TB_STATUS;

    /**
     * The table <code>school.tb_survey</code>.
     */
    public static final TB_SURVEY TB_SURVEY = zw.co.elearning.school.db.tables.TB_SURVEY.TB_SURVEY;

    /**
     * The table <code>school.tb_visit</code>.
     */
    public static final TB_VISIT TB_VISIT = zw.co.elearning.school.db.tables.TB_VISIT.TB_VISIT;

    /**
     * The table <code>school.test_kit</code>.
     */
    public static final TEST_KIT TEST_KIT = zw.co.elearning.school.db.tables.TEST_KIT.TEST_KIT;

    /**
     * The table <code>school.test_kit_batch</code>.
     */
    public static final TEST_KIT_BATCH TEST_KIT_BATCH = zw.co.elearning.school.db.tables.TEST_KIT_BATCH.TEST_KIT_BATCH;

    /**
     * The table <code>school.town</code>.
     */
    public static final TOWN TOWN = zw.co.elearning.school.db.tables.TOWN.TOWN;

    /**
     * The table <code>school.unit</code>.
     */
    public static final UNIT UNIT = zw.co.elearning.school.db.tables.UNIT.UNIT;

    /**
     * The table <code>school.vaginal_monitoring</code>.
     */
    public static final VAGINAL_MONITORING VAGINAL_MONITORING = zw.co.elearning.school.db.tables.VAGINAL_MONITORING.VAGINAL_MONITORING;

    /**
     * The table <code>school.vital</code>.
     */
    public static final VITAL VITAL = zw.co.elearning.school.db.tables.VITAL.VITAL;

    /**
     * The table <code>school.ward</code>.
     */
    public static final WARD WARD = zw.co.elearning.school.db.tables.WARD.WARD;

    /**
     * The table <code>school.zepi_drug_name</code>.
     */
    public static final ZEPI_DRUG_NAME ZEPI_DRUG_NAME = zw.co.elearning.school.db.tables.ZEPI_DRUG_NAME.ZEPI_DRUG_NAME;
}
